### ISSUE TITLE
Instalátor nefunguje na Javě 9

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#145]
Jednak je potřeba importovat JAXB modul.

Druhak při samotném zahájení instalace:

Exception in thread "IzPack - Unpacker thread" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at com.izforge.izpack.installer.unpacker.UnpackerBase.logIntro(UnpackerBase.java:253)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:285)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:242)
	at java.base/java.lang.Thread.run(Thread.java:844)

A když už jsme u toho, používáme zastaralé komponenty:

* `Found deprecated nested <param> definition(s) for 'validator' element, please migrate them to the new <configuration> format`

**Comment by triceo** [comment]
Příští verze IZPacku, pravděpodobně 5.1.3, to bude mít opravené:
https://izpack.atlassian.net/browse/IZPACK-1588

JAXB není problém, to jsem nakonec už před časem ošetřil na straně robota.
