### ISSUE TITLE
Příliš vysoké datum opuštění Zonky vygeneruje chybu ve strategii

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#219]
Caused by: java.lang.IllegalArgumentException: Loan term must be in range of <0; 84>, but was 450
	at com.github.robozonky.strategy.natural.conditions.LoanTermCondition.assertIsInRange(LoanTermCondition.java:27)
	at com.github.robozonky.strategy.natural.conditions.LoanTermCondition.<init>(LoanTermCondition.java:34)
	at com.github.robozonky.strategy.natural.conditions.LoanTermCondition.<init>(LoanTermCondition.java:39)
	at com.github.robozonky.strategy.natural.FilterSupplier.supplyFilters(FilterSupplier.java:95)
	at com.github.robozonky.strategy.natural.FilterSupplier.lambda$refreshPrimaryMarketplaceFilters$3(FilterSupplier.java:113)
	at com.github.robozonky.strategy.natural.FilterSupplier.getFilters(FilterSupplier.java:87)
	at com.github.robozonky.strategy.natural.FilterSupplier.refreshPrimaryMarketplaceFilters(FilterSupplier.java:113)
	at com.github.robozonky.strategy.natural.FilterSupplier.refreshLocked(FilterSupplier.java:143)
	at com.github.robozonky.strategy.natural.FilterSupplier.refresh(FilterSupplier.java:167)
	at com.github.robozonky.strategy.natural.FilterSupplier.<init>(FilterSupplier.java:66)
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.complexExpression(NaturalLanguageStrategyParser.java:584)
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.primaryExpression(NaturalLanguageStrategyParser.java:315)
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyService.parseWithAntlr(NaturalLanguageStrategyService.java:86)
	at com.github.robozonky.strategy.natural.GeneratedStrategyVerifier.parseWithAntlr(GeneratedStrategyVerifier.java:27)
	at cz.janhrcek.nss.RandomStrategyRenderingTest.strategyIsParsableByRobozonky(RandomStrategyRenderingTest.java:59)

**Comment by triceo** [comment]
FYI @jhrcek
