### ISSUE TITLE
Dlouhe spusteni

### ISSUE THREAD

**Issue by lukyrys** [RoboZonky/robozonky#227]
Jaky je duvod ze tahle akce po spusteni trva nekolik minut nez se robot hne.
Bezi mi to na Turris 1.1 a Java 9 openjdk, behem toho bezi proces robozonky na 100% vyuziti cpu

```
23:52:54.733 INFO  c.g.r.app.runtime.SchedulerControl Zonky servers are available, API version 0.87.0 detected.
23:58:37.425 INFO  c.g.r.app.RoboZonkyStartupNotifier ===== RoboZonky v4.4.0 at your service! =====

```

**Comment by triceo** [comment]
Můžete přiložit výpis z logu, prosím? Bez toho nemám šanci vidět, co se děje.

**Comment by triceo** [comment]
Mezitím se ozvali i další uživatelé, takže už vím, co se děje. (Ačkoliv nevím, proč zrovna teď.) Oprava bude.

**Comment by lukyrys** [comment]
@triceo  Mam pocit ze se to deje kvuli tomuto i v nove verzi 4.5.0
Tenhle bug mi delala i 4.4.0 nicmene robot funguje po chvili napise resumed a investuje

```
15:04:50.353 INFO  c.g.r.app.runtime.SchedulerControl Zonky servers are available, API version 0.88.0 detected.
15:04:55.651 INFO  c.g.r.a.c.daemon.StrategyProvider Investing strategy correctly loaded.
15:04:55.765 INFO  c.g.r.a.c.daemon.StrategyProvider Purchasing strategy correctly loaded.
15:04:55.820 INFO  c.g.r.a.c.daemon.StrategyProvider Selling strategy inactive or missing, disabling all such operations.
15:04:57.415 INFO  c.g.r.app.RoboZonkyStartupNotifier ===== RoboZonky v4.5.0-cr-1 at your service! =====
15:04:57.520 INFO  c.g.r.a.c.daemon.PortfolioUpdater Pausing RoboZonky in order to update internal data structures.
15:05:05.682 WARN  c.g.r.a.a.ZonkyApiTokenSupplier Authentication failed.
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:318)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:441)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:102)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy22.login(Unknown Source)
        at com.github.robozonky.common.remote.OAuth.lambda$login$0(OAuth.java:32)
        at com.github.robozonky.common.remote.Api.execute(Api.java:31)
        at com.github.robozonky.common.remote.OAuth.login(OAuth.java:31)
        at com.github.robozonky.app.authentication.PasswordBasedAccess.lambda$trigger$0(PasswordBasedAccess.java:40)
        at com.github.robozonky.common.remote.ApiProvider.oauth(ApiProvider.java:95)
        at com.github.robozonky.app.authentication.PasswordBasedAccess.trigger(PasswordBasedAccess.java:38)
        at com.github.robozonky.app.authentication.ZonkyApiTokenSupplier.getFreshToken(ZonkyApiTokenSupplier.java:64)
        at com.github.robozonky.app.authentication.ZonkyApiTokenSupplier.getTokenInAnyWay(ZonkyApiTokenSupplier.java:82)
        at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
        at com.github.robozonky.app.authentication.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:88)
        at com.github.robozonky.app.authentication.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:35)
        at com.github.robozonky.app.authentication.TokenBasedAccess.getToken(TokenBasedAccess.java:43)
        at com.github.robozonky.app.authentication.TokenBasedAccess.call(TokenBasedAccess.java:49)
        at com.github.robozonky.app.portfolio.Portfolio.create(Portfolio.java:68)
        at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:102)
        at com.github.robozonky.util.Backoff.execute(Backoff.java:81)
        at com.github.robozonky.util.Backoff.get(Backoff.java:94)
        at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.run(PortfolioUpdater.java:125)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.apache.http.NoHttpResponseException: api.zonky.cz:443 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:314)
        ... 28 common frames omitted
15:05:27.451 INFO  c.g.r.a.c.daemon.PortfolioUpdater RoboZonky resumed.
```

**Comment by lukyrys** [comment]
@triceo poslal jsem log na email
