### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by samurajj** [RoboZonky/robozonky#229]
Přišla mi email notifikace, že RoboZonky selhal. Poslední záznamy v logu z 6.4.2018:

04:35:18.291 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticationFilter HTTP POST Response from https://api.zonky.cz/oauth/token: 200 OK.
04:35:18.318 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
04:35:40.152 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/investments: 200 OK.
04:36:05.058 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/investments: 200 OK.
04:36:18.400 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
04:36:32.894 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/investments: 200 OK.
04:36:32.942 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/investments: 400 Bad Request.
04:36:32.942 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter Response body is: {"error":"invalid_token","error_description":"Access token expired: 44855f63-bc26-4e73-b31f-7db20df440f6"}
04:36:32.943 [rzDaemon-2] DEBUG com.github.robozonky.util.Backoff Operation failed.
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:219)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:193)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy39.items(Unknown Source)
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:57)
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:52)
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:70)
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:62)
	at com.github.robozonky.common.remote.PaginatedImpl.nextPage(PaginatedImpl.java:48)
	at com.github.robozonky.common.remote.EntitySpliterator.readNewPage(EntitySpliterator.java:101)
	at com.github.robozonky.common.remote.EntitySpliterator.tryAdvance(EntitySpliterator.java:83)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.robozonky.app.portfolio.Portfolio.create(Portfolio.java:71)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$runIt$1(PortfolioUpdater.java:102)
	at com.github.robozonky.common.remote.ApiProvider.authenticated(ApiProvider.java:123)
	at com.github.robozonky.app.authentication.TokenBasedAccess.call(TokenBasedAccess.java:49)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:102)
	at com.github.robozonky.util.Backoff.execute(Backoff.java:81)
	at com.github.robozonky.util.Backoff.get(Backoff.java:94)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.run(PortfolioUpdater.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
04:36:32.943 [rzDaemon-2] DEBUG c.g.robozonky.app.runtime.Lifecycle Asking application to die through com.github.robozonky.app.runtime.Lifecycle@5a9e6da0.
04:36:32.948 [main] DEBUG c.github.robozonky.app.ShutdownHook RoboZonky terminating with 'ERROR_UNEXPECTED' return code.
04:36:32.948 [main] DEBUG com.github.robozonky.app.Events Firing class com.github.robozonky.api.notifications.RoboZonkyCrashedEvent.
04:36:32.948 [main] DEBUG c.g.r.c.e.ListenerServiceLoader Processing 'class com.github.robozonky.app.management.JmxListenerService'.
04:36:32.948 [main] DEBUG c.g.r.c.e.ListenerServiceLoader Processing 'class com.github.robozonky.notifications.email.EmailListenerService'.
04:36:32.948 [main] DEBUG com.github.robozonky.util.Scheduler Scheduling RefreshableNotificationProperties{id='7eb9668f-8137-4022-8be3-237e71876e13'} every 300000 ms, starting in 0 ms.
04:36:32.952 [rzBackground-1] DEBUG c.g.r.n.e.RefreshableNotificationProperties Read config file '/opt/RoboZonky/robozonky-notifications-email.cfg'.
04:36:32.968 [main] DEBUG c.g.r.n.e.RoboZonkyCrashedEventListener Will send 'RoboZonky selhal!' from RoboZonky <...@...> to [...@...] through smtp.seznam.cz:465 as ...@....
04:36:34.395 [main] INFO  c.g.r.app.RoboZonkyStartupNotifier ===== RoboZonky out. =====
04:36:34.395 [main] DEBUG c.g.r.app.management.Management Unregistering MBeans.
04:36:34.396 [main] DEBUG c.g.r.app.management.Management Unregistered MBean 'com.github.robozonky:type=Runtime'.
04:36:34.396 [main] DEBUG c.g.r.app.management.Management Unregistered MBean 'com.github.robozonky:type=Operations'.
04:36:34.396 [main] DEBUG c.g.r.app.management.Management Unregistered MBean 'com.github.robozonky:type=Delinquency'.
04:36:34.396 [main] DEBUG c.g.r.app.management.Management Unregistered MBean 'com.github.robozonky:type=Portfolio'.
04:36:34.396 [main] DEBUG c.g.r.app.management.Management MBeans unregistered.
04:36:34.396 [main] DEBUG c.g.r.app.runtime.ShutdownEnabler Running with java.util.concurrent.Semaphore@2ef14fe[Permits = 0].
04:36:34.410 [Thread-1] DEBUG c.g.r.app.runtime.DaemonShutdownHook Shutdown requested through com.github.robozonky.app.runtime.Lifecycle@5a9e6da0.
04:36:34.410 [Thread-1] DEBUG c.g.robozonky.app.runtime.Lifecycle Asking application to shut down cleanly through com.github.robozonky.app.runtime.Lifecycle@5a9e6da0.
04:36:34.410 [Thread-1] DEBUG c.g.r.app.runtime.ShutdownEnabler Waiting for shutdown on java.util.concurrent.Semaphore@2ef14fe[Permits = 1].
04:36:34.410 [Thread-1] DEBUG c.g.r.app.runtime.DaemonShutdownHook Shutdown allowed.

**Comment by marek-stopka** [comment]
V masteru už je to fixnuté; zatím mi 4.5.0-SNAPSHOT běží bez problémů, nasadil jsem ho asi před 30 minutami.

**Comment by triceo** [comment]
Díky za report, @samurajj ! Velmi pravděpodobně je to stejný problém, jako #227. Právě s Markem testujeme v pull requestu #228 opravu. Pokud to dobře dopadne, brzy se objeví verze 4.5.0.CR1.

Upřímně nechápu, proč se to začalo lidem stávat teď. Nic zásadního se nezměnilo. Ale už mi o tom docela dost lidí, takže je jasný, že je to velký problém.

**Comment by samurajj** [comment]
Páni, vy jste rychlíci. Díky za to co děláte ;)
