### ISSUE TITLE
Problémy s 4.7cr1

### ISSUE THREAD

**Issue by msantavy** [RoboZonky/robozonky#272]
Chtěl bych nahlásit dva problémy s cr1, které jsem včera zkoušel nasadit.

1) Instalátor nevloží dle "Co je nového" do robozonky.cli parametr -i s cestou ke konfiguračnímu souboru. Dnes mě napadlo jej tam vložit, a maily už fungují, bohužel jediného typu, viz bod 2).

2) Po nějaké době běhu mi 2x Robozonky spadl na chybě:
13:25:46.690 [rzDaemon-1] DEBUG com.github.robozonky.util.Backoff Operation failed.
java.lang.IllegalStateException: Portfolio update failed.
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:115)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$run$5(PortfolioUpdater.java:123)
	at com.github.robozonky.util.Backoff.execute(Backoff.java:82)
	at com.github.robozonky.util.Backoff.get(Backoff.java:102)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.run(PortfolioUpdater.java:125)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unexpected missing date: 630687
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:111)
	... 10 common frames omitted
Caused by: java.lang.IllegalStateException: Unexpected missing date: 630687
	at com.github.robozonky.app.portfolio.DelinquencyCategory.lambda$getPaymentMissedDate$1(DelinquencyCategory.java:114)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.getPaymentMissedDate(DelinquencyCategory.java:114)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.isOverThreshold(DelinquencyCategory.java:69)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.lambda$update$4(DelinquencyCategory.java:143)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$IntWrappingSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.IntPipeline.toArray(Unknown Source)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.update(DelinquencyCategory.java:153)
	at com.github.robozonky.app.portfolio.Delinquencies.lambda$processNonDefaultDelinquents$9(Delinquencies.java:123)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.github.robozonky.app.portfolio.Delinquencies.processNonDefaultDelinquents(Delinquencies.java:123)
	at com.github.robozonky.app.portfolio.Delinquencies.update(Delinquencies.java:136)
	at com.github.robozonky.app.portfolio.Delinquencies.update(Delinquencies.java:163)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$null$1(PortfolioUpdater.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:107)
	... 10 common frames omitted

Jinak se moc těším na rich textové maily. Poté co jsem je rozchodil, se mi polovina portfolia špatně zalamuje.

**Comment by triceo** [comment]
Zdravím a díky za report!
První problém už jsem tenhle týden opravil. 
Ten druhý bude oříšek - pokud máte log, rád se na něj podívám.

**Comment by msantavy** [comment]
Přeju dobré dopoledne. Lehce anonymizovaný log dodávám:

[robozonky.log](https://github.com/RoboZonky/robozonky/files/2191736/robozonky.log)

**Comment by triceo** [comment]
@msantavy Můžete se, prosím, podívat mezi svoje zesplatněné půjčky? Máte tušení, jestli nějaká přibyla nedávno? Pokud ano, v jakém je stavu? Byla předtím v prodlení, nebo byla zdravá?

Není mi úplně zřejmé, co se v tomhle případě děje, ale je zřejmé, že to souvisí s nějakou investicí, která je nově zesplatněná.

**Comment by msantavy** [comment]
Na začátek dodám, protože to možná nevyznělo, s verzí 4.6.4 takový problém nemám.

Nejsem si toho příliš vědom. A není mi ani úplně jasné kam bych se měl podívat. Zkouším to teda přes export do Excelu, kde tedy nevidím datum zesplatnění, ale ručním porovnáváním oproti stavu z 2.7. tam mám opravdu rozdíl v zesplatněné půjčce: 
zonky134444 | Honda
https://app.zonky.cz/auto-moto/honda-105614
Ale pozor - je zesplatněná v excelu z 2.7., ale v dnešním už ne! V dnešním je vedena jako zaplacená.
Po komplikovaném hledání na zonky.cz jsem zjistil, že byla zaplacená 5.7.

Pomůže Vám to?

**Comment by triceo** [comment]
@msantavy Díky. :-) Jo, to bude nějak souviset - nečekaná situace: půjčka je zesplatněná a okamžitě zaplacená. Robot se s tím bude muset umět vyrovnat.

Uvidím, co s tím. V tomhle kódu byly ve verzi 4.7 nějaké změny, takže je možné, že se to teď chová jinak než ve 4.6.

**Comment by msantavy** [comment]
Dobré ráno.

Robozonky 4.7.2. Stejná chyba znovu. Začalo to až dnes v 4:06, do té doby ok, skončilo pádem.

java.lang.IllegalStateException: Portfolio update failed.
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:115)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$run$5(PortfolioUpdater.java:123)
	at com.github.robozonky.util.Backoff.execute(Backoff.java:82)
	at com.github.robozonky.util.Backoff.get(Backoff.java:102)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.run(PortfolioUpdater.java:125)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unexpected missing date: 630687
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:111)
	... 10 common frames omitted
Caused by: java.lang.IllegalStateException: Unexpected missing date: 630687
	at com.github.robozonky.app.portfolio.DelinquencyCategory.lambda$getPaymentMissedDate$1(DelinquencyCategory.java:114)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.getPaymentMissedDate(DelinquencyCategory.java:114)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.isOverThreshold(DelinquencyCategory.java:69)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.lambda$update$4(DelinquencyCategory.java:143)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$IntWrappingSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.IntPipeline.toArray(Unknown Source)
	at com.github.robozonky.app.portfolio.DelinquencyCategory.update(DelinquencyCategory.java:153)
	at com.github.robozonky.app.portfolio.Delinquencies.lambda$processNonDefaultDelinquents$1(Delinquencies.java:98)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.github.robozonky.app.portfolio.Delinquencies.processNonDefaultDelinquents(Delinquencies.java:98)
	at com.github.robozonky.app.portfolio.Delinquencies.update(Delinquencies.java:120)
	at com.github.robozonky.app.portfolio.Delinquencies.update(Delinquencies.java:154)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$null$1(PortfolioUpdater.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:107)
	... 10 common frames omitted

**Comment by triceo** [comment]
@msantavy Dokážete nějak zjistit, co je `630687` za investici? Bude to muset být nějaká velmi speciální situace, se kterou se robot stále nedokáže vyrovnat - nejspíš proto, že mě nenapadlo, jsem nevěděl, že je vůbec možná.

Bohužel bez přístupu k Vašemu účtu nemám nejmenší možnost zjistit, o co se jedná, protože čísla investic jsou specifická pro každého uživatele.

Dovedu si představit, že bych Vám připravil speciální verzi robota, která bude v takovém případě vypisovat daleko víc informací, takže tu investici budete mít jednodušší najít. Ale bez toho, abych věděl, o jakou investici se jedná a v jakém je přesně stavu, se nepohneme z místa.

**Comment by msantavy** [comment]
Ještě jsem si vzpomněl, že během dovolené mi spadl i 4.6.4. A s podobnou chybou, možná při 
zpracování blokovaných půjček. Zde část logu z toho dne (29.6.)

Nemám robozonky v eclipse na debug, ale můžu se případně pokusit to nějak hacknout a vypsat víc informací.

04:13:01.743 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet/transactions?transaction.transactionDate__gte=2018-06-29: 200 OK.
04:13:01.883 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet/blocked-amounts: 200 OK.
04:13:01.883 [rzDaemon-2] DEBUG c.g.r.app.portfolio.TransactionLog Processing blocked amount: com.github.robozonky.api.remote.entities.BlockedAmount@8893bb9[amount=800.00,discount=<null>,id=4508368,loanId=268913,category=INVESTMENT,loanName=GarĂˇĹľ -DĂ­lna,dateStart=2018-06-28T18:06:22.279+02:00].
04:13:01.883 [rzDaemon-2] DEBUG c.g.r.app.portfolio.TransactionLog There was no corresponding synthetic, updating rating shares.
04:13:01.930 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/loans/268913: 200 OK.
04:13:01.930 [rzDaemon-2] DEBUG c.g.r.app.portfolio.TransactionLog Processing blocked amount: com.github.robozonky.api.remote.entities.BlockedAmount@58e59d3a[amount=800.00,discount=<null>,id=4506837,loanId=269340,category=INVESTMENT,loanName=Rekonstrukce chaty pro budoucĂ­ pronĂˇjem,dateStart=2018-06-28T15:16:48.638+02:00].
04:13:01.930 [rzDaemon-2] DEBUG c.g.r.app.portfolio.TransactionLog There was no corresponding synthetic, updating rating shares.
04:13:01.977 [rzDaemon-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/loans/269340: 404 Not Found.
04:13:01.993 [rzDaemon-2] DEBUG com.github.robozonky.util.Backoff Operation failed.
java.lang.IllegalStateException: Portfolio update failed.
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:112)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$run$5(PortfolioUpdater.java:120)
	at com.github.robozonky.util.Backoff.execute(Backoff.java:81)
	at com.github.robozonky.util.Backoff.get(Backoff.java:94)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.run(PortfolioUpdater.java:122)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:110)
	... 10 common frames omitted
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:223)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:193)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy42.item(Unknown Source)
	at com.github.robozonky.common.remote.Zonky.lambda$getLoan$4(Zonky.java:157)
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:60)
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:55)
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:50)
	at com.github.robozonky.common.remote.Zonky.getLoan(Zonky.java:157)
	at com.github.robozonky.app.portfolio.TransactionLog.lambda$getLoanRating$1(TransactionLog.java:86)
	at com.github.robozonky.common.remote.ApiProvider.authenticated(ApiProvider.java:121)
	at com.github.robozonky.app.authentication.TokenBasedTenant.call(TokenBasedTenant.java:63)
	at com.github.robozonky.app.portfolio.TransactionLog.getLoanRating(TransactionLog.java:86)
	at com.github.robozonky.app.portfolio.TransactionLog.updateRatingShare(TransactionLog.java:95)
	at com.github.robozonky.app.portfolio.TransactionLog.processBlockedAmount(TransactionLog.java:146)
	at com.github.robozonky.app.portfolio.TransactionLog.lambda$update$10(TransactionLog.java:171)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at com.github.rutledgepaulv.pagingstreams.PagingStreams$PagingSpliterator.forEachRemaining(PagingStreams.java:126)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.github.robozonky.app.portfolio.TransactionLog.update(TransactionLog.java:169)
	at com.github.robozonky.app.portfolio.Portfolio.updateTransactions(Portfolio.java:114)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$null$1(PortfolioUpdater.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
	at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:106)
	... 10 common frames omitted

**Comment by triceo** [comment]
Tahle poslední chyba není chyba v robotu - je to chyba v cache Zonky. Občas jejich cache tvrdí, že nějaká půjčka neexistuje, přestože jí máte v portfoliu. Tomuhle se přízpůsobovat nebudu, tohle si musí opravit Zonky. (A zdá se, že už to vyřešili.)

**Comment by msantavy** [comment]
Tak je to tahle půjčka: https://app.zonky.cz/marketplace/detail/79103/
Dle Excelu dávno (v lednu) splacená. Co je možná na ní zajímavého (?) dle Wallet.xls, že má dvakrát splátku s nulovým úrokem (?!)...

Tady kus z logu:
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unexpected missing date: com.github.robozonky.api.remote.entities.sanitized.MutableInvestmentImpl@7b1e9a95[loanId=79103,id=630687,currentTerm=10,originalTerm=10,remainingMonths=0,daysPastDue=1,nextPaymentDate=<null>,investmentDate=<null>,canBeOffered=false,isOnSmp=false,isInsuranceActive=false,areInstalmentsPostponed=false,isInWithdrawal=false,originalPrincipal=1400.00,interestRate=0.059900,paidPrincipal=1400.00,duePrincipal=0,paidInterest=37.50,dueInterest=0,expectedInterest=37.50,paidPenalty=0,remainingPrincipal=0,smpFee=<null>,smpSoldFor=<null>,rating=AAA,status=ACTIVE,paymentStatus=PAID,insuranceHistory=[],investmentDateSupplier=com.github.robozonky.api.remote.entities.sanitized.MutableInvestmentImpl$$Lambda$351/1245977610@66b5ac3a]

**Comment by triceo** [comment]
Tak to je skutečně poměrně neuvěřitelná situace. :-) Ok, díky - uvidím, co se s tím dá dělat.

**Comment by triceo** [comment]
@marek-stopka Ten problém tady bude spíš v tom, že ta půjčka je evidovaná jako splacená a přesto se nějakým zázrakem dostala do kódu, který řeší delikvence. Budu to muset prozkoumat blíž.
