### ISSUE TITLE
Některé investice se chybně dostávají do delikvencí

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#279]
Ze #272:

13:25:46.690 [rzDaemon-1] DEBUG com.github.robozonky.util.Backoff Operation failed.
java.lang.IllegalStateException: Portfolio update failed.
at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:115)
at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$run$5(PortfolioUpdater.java:123)
at com.github.robozonky.util.Backoff.execute(Backoff.java:82)
at com.github.robozonky.util.Backoff.get(Backoff.java:102)
at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.run(PortfolioUpdater.java:125)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unexpected missing date: 630687
at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:111)
... 10 common frames omitted
Caused by: java.lang.IllegalStateException: Unexpected missing date: 630687
at com.github.robozonky.app.portfolio.DelinquencyCategory.lambda$getPaymentMissedDate$1(DelinquencyCategory.java:114)
at java.base/java.util.Optional.orElseThrow(Unknown Source)
at com.github.robozonky.app.portfolio.DelinquencyCategory.getPaymentMissedDate(DelinquencyCategory.java:114)
at com.github.robozonky.app.portfolio.DelinquencyCategory.isOverThreshold(DelinquencyCategory.java:69)
at com.github.robozonky.app.portfolio.DelinquencyCategory.lambda$update$4(DelinquencyCategory.java:143)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.StreamSpliterators$IntWrappingSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
at java.base/java.util.stream.IntPipeline.toArray(Unknown Source)
at com.github.robozonky.app.portfolio.DelinquencyCategory.update(DelinquencyCategory.java:153)
at com.github.robozonky.app.portfolio.Delinquencies.lambda$processNonDefaultDelinquents$9(Delinquencies.java:123)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
at com.github.robozonky.app.portfolio.Delinquencies.processNonDefaultDelinquents(Delinquencies.java:123)
at com.github.robozonky.app.portfolio.Delinquencies.update(Delinquencies.java:136)
at com.github.robozonky.app.portfolio.Delinquencies.update(Delinquencies.java:163)
at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.lambda$null$1(PortfolioUpdater.java:103)
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
at com.github.robozonky.app.configuration.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:107)
... 10 common frames omitted

**Comment by triceo** [comment]
Teď k tomu, co se děje - investice 630687 se vztahuje k velmi staré půjčce 79103. Tato půjčka, z nějakého důvodu, odpovídá tomuhle filtru a proto se ukazuje mezi delikvencemi, přestože už je dávno splacená:

    new Select()
                                                          .equals("loan.unpaidLastInst", "true")
                                                          .equals("status", "ACTIVE")

To pak vede k celé řadě špatných věcí, kterým jde předejít, pokud se do kódu pro řešení delikvencí dostanou skutečně jen delikvence. Zonky se na delikvence ptá takhle:

    new Select()
                                                          .in("loan.status", "ACTIVE", "PAID_OFF")
                                                          .equals("loan.unpaidLastInst", "true")
                                                          .equals("status", "ACTIVE")

Pracovní hypotéza je, že problém zmizí, když změním ten dotaz na následujícím místě:

https://github.com/RoboZonky/robozonky/blob/master/robozonky-app/src/main/java/com/github/robozonky/app/portfolio/Delinquencies.java#L143

Můžete to, @msantavy, prosím vyzkoušet? Jediný, komu se to děje, jste evidentně Vy.

**Comment by msantavy** [comment]
Jasně, zkusím, ale k počítači se dnes nedostanu, až zítra dopoledne. Dám
hned vědět.

Dne út 17. čvc 2018 17:42 uživatel Lukáš Petrovický <
notifications@github.com> napsal:

**Comment by triceo** [comment]
@msantavy Když se podíváte na ten nový filtr, přidal jsem tam pole `loan.status` tak, jak ho tam má Zonky. Nicméně když se podíváte do API, tak `loan` endpoint žádný `status` field nemá. :-) Z toho usuzuju, že to je nějaký implementační detail Zonky, který jim omylem probublal "ven". Nevím, k čemu je nebo jaké jsou jeho vlastnosti. 

Nicméně si z toho odnáším, že problém je vyřešený a chování _RoboZonky_ teď na 100 % odpovídá chování webu Zonky. Což je dobrá zpráva. Takže někdy dneska vydám 4.7.4. 

Díky za spolupráci!

**Comment by msantavy** [comment]
Super, Také děkuji,
