### ISSUE TITLE
RoboZonky raises exception while trying to send an e-mail notification

### ISSUE THREAD

**Issue by mark-stopka** [RoboZonky/robozonky#285]
RoboZonky today invested in 3 different loans, but I got only two e-mail notifications so I checked the log and found following exception...
```
21:44:42.341 [rzDaemon-2] WARN  com.github.robozonky.app.Events Listener failed: com.github.robozonky.notifications.listeners.InvestmentMadeEventListener@7903f2df.
java.lang.IllegalStateException: Event processing failed.
	at com.github.robozonky.notifications.listeners.AbstractListener.handle(AbstractListener.java:169)
	at com.github.robozonky.app.Events.fire(Events.java:69)
	at com.github.robozonky.app.Events.lambda$fire$2(Events.java:138)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.github.robozonky.app.Events.fire(Events.java:137)
	at com.github.robozonky.app.investing.Session.invest(Session.java:174)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.TreeMap$ValueSpliterator.tryAdvance(TreeMap.java:2921)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.github.robozonky.app.investing.Session.invest(Session.java:103)
	at com.github.robozonky.app.investing.Session.invest(Session.java:90)
	at com.github.robozonky.app.investing.Investing.execute(Investing.java:72)
	at com.github.robozonky.app.investing.Investing.execute(Investing.java:33)
	at com.github.robozonky.app.util.StrategyExecutor.invest(StrategyExecutor.java:102)
	at com.github.robozonky.app.util.StrategyExecutor.lambda$apply$0(StrategyExecutor.java:111)
	at java.util.Optional.map(Optional.java:215)
	at com.github.robozonky.app.util.StrategyExecutor.apply(StrategyExecutor.java:111)
	at com.github.robozonky.app.configuration.daemon.InvestingDaemon.execute(InvestingDaemon.java:85)
	at com.github.robozonky.app.configuration.daemon.DaemonOperation.run(DaemonOperation.java:61)
	at com.github.robozonky.app.configuration.daemon.Skippable.run(Skippable.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> data.loanName  [in template "core.ftl" at line 3, column 62]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${data.loanName?cap_first}  [in template "core.ftl" in macro "idLoan" at line 3, column 60]
	- Reached through: @idLoan data=data  [in template "investment-made.ftl" at line 1, column 11]
	- Reached through: #include embed  [in template "core.ftl" at line 54, column 9]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:467)
	at freemarker.core.EvalUtil.coerceModelToStringOrUnsupportedMarkup(EvalUtil.java:422)
	at freemarker.core.Expression.evalAndCoerceToStringOrUnsupportedMarkup(Expression.java:123)
	at freemarker.core.BuiltInForString.getTargetString(BuiltInForString.java:34)
	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:29)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:366)
	at freemarker.core.Environment.invoke(Environment.java:775)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.include(Environment.java:2582)
	at freemarker.core.Include.accept(Include.java:171)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.process(Environment.java:309)
	at freemarker.template.Template.process(Template.java:384)
	at com.github.robozonky.notifications.templates.TemplateProcessor.process(TemplateProcessor.java:65)
	at com.github.robozonky.notifications.templates.TemplateProcessor.processHtml(TemplateProcessor.java:76)
	at com.github.robozonky.notifications.listeners.AbstractListener$1.getMessage(AbstractListener.java:147)
	at com.github.robozonky.notifications.AbstractTargetHandler.offer(AbstractTargetHandler.java:105)
	at com.github.robozonky.notifications.listeners.AbstractListener.handle(AbstractListener.java:166)
	... 67 common frames omitted

```

**Comment by triceo** [comment]
Nice. Can you find out from the log which loan it was trying to invest into at that moment?
This error message is saying that there was no *loan name* on the loan, and that just sounds like nonsense.

**Comment by mark-stopka** [comment]
Hi, sadly it's not a non-sense, must be a problem at Zonky side -
https://app.zonky.cz/id/283426

--
Best regards / S pozdravem,
Bc. Mark Stopka, BBA

mobile: +420 704 373 561

**Comment by triceo** [comment]
This was a Zonky bug. The loan is now back on-line.
