### ISSUE TITLE
Instalace selže při ověřování strategie

### ISSUE THREAD

**Issue by zdeneksuchan** [RoboZonky/robozonky#295]
09:42:10.417 INFO  c.g.r.i.StrategySettingsValidator Starting validation.
09:42:10.432 ERROR c.g.r.i.StrategySettingsValidator Uncaught exception.
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.github.robozonky.common.extensions.StrategyLoader
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.github.robozonky.installer.AbstractValidator.validateData(AbstractValidator.java:43)
        at com.github.robozonky.installer.StrategySettingsValidator.validateData(StrategySettingsValidator.java:28)
        at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:504)
        at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:486)
        at com.izforge.izpack.installer.panel.AbstractPanelView.validateData(AbstractPanelView.java:429)
        at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:259)
        at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:234)
        at com.izforge.izpack.installer.panel.AbstractPanels.executeValidationActions(AbstractPanels.java:564)
        at com.izforge.izpack.installer.panel.AbstractPanels.isValid(AbstractPanels.java:178)
        at com.izforge.izpack.installer.panel.AbstractPanels.next(AbstractPanels.java:228)
        at com.izforge.izpack.installer.console.ConsoleInstaller.run(ConsoleInstaller.java:155)
        at com.izforge.izpack.installer.bootstrap.InstallerConsole.run(InstallerConsole.java:86)
        at com.izforge.izpack.installer.bootstrap.Installer.launchInstall(Installer.java:302)
        at com.izforge.izpack.installer.bootstrap.Installer.start(Installer.java:238)
        at com.izforge.izpack.installer.bootstrap.Installer.main(Installer.java:78)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.robozonky.common.extensions.StrategyLoader
        at com.github.robozonky.cli.StrategyValidationFeature.test(StrategyValidationFeature.java:85)
        at com.github.robozonky.installer.StrategySettingsValidator.validateDataPossiblyThrowingException(StrategySettingsValidator.java:49)
        at com.github.robozonky.installer.AbstractValidator.lambda$validateData$0(AbstractValidator.java:41)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
09:42:10.432 INFO  c.g.r.i.StrategySettingsValidator Finished validation.
Ověrování selhalo:
Nebyla zadána strategie.

Windows10 English (UK) region
zkoušena grafická i consolová instalace (4.7.5 i 4.7.6)
zkoušeno několik různých strategii (vzorová, vygenerovaná, psaná ručně)
zkoušeny různé lokální umístění strategie (pouze načítání ze souboru)
nezkoušeno načítání strategie z webu
[robozonky-strategy.txt](https://github.com/RoboZonky/robozonky/files/2289564/robozonky-strategy.txt)

**Comment by triceo** [comment]
Díky, podívám se na to.

**Comment by triceo** [comment]
@zdeneksuchan Bohužel se mi problém nepodařilo zreplikovat u sebe. Soubor strategie, který posíláte, obsahuje chybu - není platný. (Minimální podíly ratingů na portfoliu musí dát dohromady 100 %.)  Ale to je podle mého názoru vedlejší, protože ta výjimka, kterou posíláte, s tím nemůže nijak souviset.

Můžu vědět, jakou používáte verzi Javy? Já to zkoušel na Javě 10.
Které obrazovky jste použil? Nastavení e-mailu? Zonkoid? Nějaké další?

**Comment by triceo** [comment]
@zdeneksuchan Připravil jsem Vám speciální instalátor:
https://drive.google.com/file/d/1Iu8IVDhK8eB-1w1BExgQ-RgHn9GsZUw0/view?usp=sharing

Sice ten problém nevyřeší - protože nevím, co ten problém je - ale poskytne nám víc informací. Stáhněte si, prosím, tenhle nový instalátor, a udělejte to stejné, co jste dělal doteď. Pak mi pošlete tu novou chybu - tentokrát bude detailnější.

**Comment by zdeneksuchan** [comment]
@triceo Dekuji za zajem, odpovedi postupne
- windows mam 64bit, javu mam nainstalovanou verzi 8 Update 181 (Oracle) 32bit, je to umyslne kuli 32b java programu, ktery potrebuji spoustet (zkusim doinstalovat i 64b javu?)
- zadne dalsi nastaveni nezaskrtnuta (instalacni adresar, komunikace se Zonky, investicni strategie
- se specialni verzi instalatoru pozoruji dve veci
-- pri overovanini strategie uz se nevyhodi neosetrena vyjimka jako drive
-- instalator opet upozorni na neexistujici strategii, presto me necha doinstalovat

![2018-08-16 17_10_53-window](https://user-images.githubusercontent.com/13870513/44218235-93f19d00-a179-11e8-8e62-080df585511d.png)
![2018-08-16 17_13_11-window](https://user-images.githubusercontent.com/13870513/44218181-7290b100-a179-11e8-9362-623215541645.png)

**Comment by mark-stopka** [comment]
Ta URL vypadá poměrně zvláštně... Spíše jako e-mail, než FQDN URI...

--
Best regards / S pozdravem,
Bc. Mark Stopka, BBA

mobile: +420 704 373 561

2018-08-16 17:32 GMT+02:00 Iceek <notifications@github.com>:

**Comment by zdeneksuchan** [comment]
Ano vypada. Je to zpusobene umistenim v adresari pro google drive pojmenovanem po emailu. Take me napadla souvislost a zkousel jsem i jina umisteni, abych toto vyloucil.

**Comment by triceo** [comment]
@zdeneksuchan Tu verzi robota, kterou jste právě nainstaloval, doporučuji vážně nepoužívat. :-) Nicméně když do adresáře `Dist` rozbalíte RoboZonky 4.7.6 ze ZIPu, mělo by to fungovat.

Co se té původní chyby týká - nevím, co to bylo, a stalo se to někde uvnitř Javy. Myslím, že to byla nějaká podivná dočasná okolnost na vašem systému. Pokud se to nestane znovu, nechám to být a tuhle issue zavřu. Ukáže-li se to znovu, můžete to znovu otevřít.

Každopádně díky za report!

**Comment by zdeneksuchan** [comment]
Po nahrazeni verze 4.8.0-SNAPSHOT verzi 4.7.6 ze ZIPu jsem opet v nefunkcnim stavu. Nicmene, bude to, stejne jako problem s instalaci, pravdepodobne problem na mem PC, protoze pokud by to trapilo vice lidi, asi by jste to vedel.
07:20:12.179 INFO  c.g.r.app.runtime.SchedulerControl Zonky servers are available, API version 0.107.0 detected.
07:20:12.257 INFO  c.g.r.app.configuration.CommandLine Notifications are not set up.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.github.robozonky.app.configuration.OperatingMode.configure(OperatingMode.java:99)
        at com.github.robozonky.app.configuration.CommandLine.lambda$newApplicationConfiguration$0(CommandLine.java:122)
        at java.util.Optional.flatMap(Unknown Source)
        at com.github.robozonky.app.configuration.CommandLine.newApplicationConfiguration(CommandLine.java:122)
        at com.github.robozonky.app.configuration.CommandLine.parseUnsafe(CommandLine.java:104)
        at com.github.robozonky.app.configuration.CommandLine.parse(CommandLine.java:84)
        at com.github.robozonky.app.App.configure(App.java:100)
        at com.github.robozonky.app.App.main(App.java:95)
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\zdenek.suchan\AppData\Local\Application Data
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(Unknown Source)
        at java.nio.file.FileTreeIterator.hasNext(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
        at com.github.robozonky.util.FileUtil.findFolder(FileUtil.java:48)
        at com.github.robozonky.common.extensions.ExtensionsManager.retrieveExtensionClassLoader(ExtensionsManager.java:47)
        at com.github.robozonky.common.extensions.ExtensionsManager.getServiceLoader(ExtensionsManager.java:63)
        at com.github.robozonky.common.extensions.ExtensionsManager.getServiceLoader(ExtensionsManager.java:58)
        at com.github.robozonky.common.extensions.ListenerServiceLoader.<clinit>(ListenerServiceLoader.java:40)
        ... 8 more
Caused by: java.nio.file.AccessDeniedException: C:\Users\zdenek.suchan\AppData\Local\Application Data
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
        at java.nio.file.Files.newDirectoryStream(Unknown Source)
        at java.nio.file.FileTreeWalker.visit(Unknown Source)
        at java.nio.file.FileTreeWalker.next(Unknown Source)
        ... 23 more

**Comment by triceo** [comment]
`Caused by: java.nio.file.AccessDeniedException: C:\Users\zdenek.suchan\AppData\Local\Application Data`

Tohle je zcela určitě nějaký problém na Vašem počítači. (A teď je vidět, že je to ten stejný problém, co jste měl předtím.)

**Comment by triceo** [comment]
@zdeneksuchan ^^^

**Comment by triceo** [comment]
(Nicméně je možné, že se robotu nelíbí ta mezera. To asi půjde opravit.)
