### ISSUE TITLE
Robot přestal investovat

### ISSUE THREAD

**Issue by shakewell9** [RoboZonky/robozonky#331]
Dobrý den, nejsem programátor tak se předem omlouvám jestli je můj problém příliš banální. V úterý jsem poprvé instalovat Rozozonky a první den to fungovalo perfektně, byl jsem nadšený. Nicméně od druhého dne robot přestal investovat. Z logu usuzuji, že je problém s tím, že není schopen načíst tržiště,

DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/loans/316612: 404 Not Found

 zatímco ostatní info např. o zůstatku v peněžence atp. načte, kousek logu posílám níže. Je problém u mě, na zonky nebo někde jinde. Předem díky za odpověď.

17:59:16.259 [rzDaemon-1] DEBUG c.g.r.a.d.BlockedAmountProcessor Found: com.github.robozonky.api.remote.entities.BlockedAmount@10b6fcb7[amount=200.00,discount=<null>,id=5388572,loanId=316612,category=INVESTMENT,loanName=Anonym,dateStart=2018-10-09T13:11:59.974+02:00].
17:59:16.306 [rzDaemon-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/loans/316612: 404 Not Found.
17:59:16.306 [rzDaemon-1] DEBUG com.github.robozonky.util.Backoff Operation failed.
java.lang.IllegalStateException: Portfolio update failed.
	at com.github.robozonky.app.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:116) [robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.PortfolioUpdater.lambda$null$6(PortfolioUpdater.java:130) [robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.util.Backoff.execute(Backoff.java:85) [robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.util.Backoff.get(Backoff.java:105) [robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.PortfolioUpdater.lambda$run$7(PortfolioUpdater.java:132) [robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.util.IoUtil.tryConsumer(IoUtil.java:60) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.PortfolioUpdater.run(PortfolioUpdater.java:129) [robozonky-app-4.9.0.jar:4.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[na:1.8.0_181]
	at com.github.robozonky.app.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:112) [robozonky-app-4.9.0.jar:4.9.0]
	... 13 common frames omitted
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:221) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:191) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-3.6.1.Final.jar:3.6.1.Final]
	at com.sun.proxy.$Proxy40.item(Unknown Source) ~[na:na]
	at com.github.robozonky.common.remote.Zonky.lambda$getLoan$8(Zonky.java:179) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:68) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:61) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:56) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.common.remote.Zonky.getLoan(Zonky.java:179) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.LoanCache.lambda$null$5(LoanCache.java:99) ~[robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.common.remote.ApiProvider.call(ApiProvider.java:138) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.authentication.TokenBasedTenant.call(TokenBasedTenant.java:64) ~[robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.LoanCache.lambda$getLoan$6(LoanCache.java:99) ~[robozonky-app-4.9.0.jar:4.9.0]
	at java.util.Optional.orElseGet(Unknown Source) ~[na:1.8.0_181]
	at com.github.robozonky.app.daemon.LoanCache.getLoan(LoanCache.java:98) ~[robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.BlockedAmountProcessor.lambda$readBlockedAmounts$3(BlockedAmountProcessor.java:62) ~[robozonky-app-4.9.0.jar:4.9.0]
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source) ~[na:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_181]
	at com.github.rutledgepaulv.pagingstreams.PagingStreams$PagingSpliterator.forEachRemaining(PagingStreams.java:126) ~[paging-streams-0.8.jar:na]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:1.8.0_181]
	at com.github.robozonky.app.daemon.BlockedAmountProcessor.readBlockedAmounts(BlockedAmountProcessor.java:61) ~[robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.BlockedAmountProcessor.create(BlockedAmountProcessor.java:48) ~[robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.BlockedAmountProcessor.lambda$createLazy$0(BlockedAmountProcessor.java:54) ~[robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.util.LazyInitialized.lambda$get$2(LazyInitialized.java:58) ~[robozonky-common-4.9.0.jar:4.9.0]
	at java.util.concurrent.atomic.AtomicReference.updateAndGet(Unknown Source) ~[na:1.8.0_181]
	at com.github.robozonky.util.LazyInitialized.get(LazyInitialized.java:54) ~[robozonky-common-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.PortfolioUpdater.lambda$create$1(PortfolioUpdater.java:77) [robozonky-app-4.9.0.jar:4.9.0]
	at com.github.robozonky.app.daemon.PortfolioUpdater.lambda$null$2(PortfolioUpdater.java:104) [robozonky-app-4.9.0.jar:4.9.0]
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[na:1.8.0_181]
	at java.util.concurrent.CompletableFuture.thenApply(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:1.8.0_181]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.reduce(Unknown Source) ~[na:1.8.0_181]
	at com.github.robozonky.app.daemon.PortfolioUpdater.runIt(PortfolioUpdater.java:108) [robozonky-app-4.9.0.jar:4.9.0]
	... 13 common frames omitted
17:59:16.306 [rzDaemon-1] DEBUG com.github.robozonky.util.Backoff Will wait for 1024000 milliseconds.
17:59:23.919 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:23.934 [rzBackground-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:26.836 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:29.488 [rzBackground-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:34.464 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:40.533 [rzBackground-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:43.278 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:47.334 [rzBackground-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
17:59:59.752 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
18:00:03.433 [rzBackground-2] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.
18:00:08.317 [rzBackground-1] DEBUG c.g.r.c.remote.AuthenticatedFilter HTTP GET Response from https://api.zonky.cz/users/me/wallet: 200 OK.

**Comment by triceo** [comment]
Zdravím. Předně díky za report - bohužel Vás nepotěším. Chyba je na Zonky serveru, konkrétně v půjčce 316612. Vy jí sice máte v portfoliu, ale Zonky tvrdí, že neexistuje. To je jasný nesmysl, a Zonky se to občas stává - mají zkrátka nějakou nekonzistentní cache.

Bohužel neexistuje nic, co bych s tím mohl na mé straně udělat. Většinou se ten problém rychle sám spraví.

**Comment by triceo** [comment]
Teď jsem si půjčku otevřel a zdá se, že je dostupná - takže robot by se měl sám spravit.
