### ISSUE TITLE
stonky integrace nevytvori soubor na gdrive

### ISSUE THREAD

**Issue by vvvlc** [RoboZonky/robozonky#406]
Ahoj,
obcas se mi stane, ze se mi nevytvori stonky soubor na gdrive.

Litaji tam tyto vyjimky  log v priloze.
Skoro bych rekl, ze se tam opakovane ceka na dobehnuti exportu, ale ty asi nedobehnou ve stanovenem case. Slo by tam pridat dalsi opakovani?
Naposled se mi stalo ze to 3 dny nic neexportovalo.
A nebo je taky mozny, ze vsechny robozonky najednou daji pozadavek na generovani exportu a Zonky api to nestiha.

```
java.lang.IllegalStateException: Download not yet ready: INVESTMENTS
	at com.github.robozonky.integrations.stonky.Export.lambda$download$a8ecb467$1(Export.java:56)
	at io.vavr.control.Try$WithResources1.lambda$of$97fea75d$1(Try.java:1203)
	at io.vavr.control.Try.of(Try.java:75)
	at io.vavr.control.Try$WithResources1.of(Try.java:1201)
	at com.github.robozonky.integrations.stonky.Export.download(Export.java:52)
	at com.github.robozonky.integrations.stonky.Export.lambda$new$0(Export.java:47)
	at com.github.robozonky.common.remote.ApiProvider.call(ApiProvider.java:130)
	at com.github.robozonky.app.tenant.PowerTenantImpl.call(PowerTenantImpl.java:83)
	at com.github.robozonky.integrations.stonky.Export.lambda$download$1(Export.java:64)
	at io.vavr.control.Try.of(Try.java:75)
	at io.vavr.control.Try.ofSupplier(Try.java:92)
	at com.github.robozonky.common.async.Backoff.execute(Backoff.java:82)
	at com.github.robozonky.common.async.Backoff.get(Backoff.java:95)
	at com.github.robozonky.integrations.stonky.Export.lambda$download$3(Export.java:67)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalStateException: Download not yet ready: WALLET
	at com.github.robozonky.integrations.stonky.Export.lambda$download$a8ecb467$1(Export.java:56)
	at io.vavr.control.Try$WithResources1.lambda$of$97fea75d$1(Try.java:1203)
	at io.vavr.control.Try.of(Try.java:75)
	at io.vavr.control.Try$WithResources1.of(Try.java:1201)
	at com.github.robozonky.integrations.stonky.Export.download(Export.java:52)
	at com.github.robozonky.integrations.stonky.Export.lambda$new$0(Export.java:47)
	at com.github.robozonky.common.remote.ApiProvider.call(ApiProvider.java:130)
	at com.github.robozonky.app.tenant.PowerTenantImpl.call(PowerTenantImpl.java:83)
	at com.github.robozonky.integrations.stonky.Export.lambda$download$1(Export.java:64)
	at io.vavr.control.Try.of(Try.java:75)
	at io.vavr.control.Try.ofSupplier(Try.java:92)
	at com.github.robozonky.common.async.Backoff.execute(Backoff.java:82)
	at com.github.robozonky.common.async.Backoff.get(Backoff.java:95)
	at com.github.robozonky.integrations.stonky.Export.lambda$download$3(Export.java:67)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.lang.Thread.run(Thread.java:834)
...
23:04:26.169 [rzBackground-2] WARN  c.g.r.integrations.stonky.Stonky Failed integrating with Stonky.
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Supplier failed.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.github.robozonky.integrations.stonky.Stonky.run(Stonky.java:189)
	at com.github.robozonky.integrations.stonky.Stonky.apply(Stonky.java:203)
	at com.github.robozonky.integrations.stonky.StonkyJob.lambda$new$0(StonkyJob.java:34)
	at com.github.robozonky.integrations.stonky.StonkyJob$StonkyPayload.accept(StonkyJob.java:73)
	at com.github.robozonky.integrations.stonky.StonkyJob$StonkyPayload.accept(StonkyJob.java:69)
	at com.github.robozonky.app.daemon.DaemonInvestmentMode.lambda$null$2(DaemonInvestmentMode.java:95)
	at com.github.robozonky.app.daemon.Skippable.run(Skippable.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Supplier failed.
	at com.github.robozonky.integrations.stonky.Util.lambda$wrap$1(Util.java:109)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 1 common frames omitted
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "location" : "fileId",
    "locationType" : "parameter",
    "message" : "File not found: 1aW_c-1nUXb4B8S5voxNTWhL982KRQJ6czRccDuPnzIoLtQhss.",
    "reason" : "notFound"
  } ],
  "message" : "File not found: 1aW_c-1nUXb4B8S5voxNTWhL982KRQJ6czRccDuPnzIoLtQhss."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.github.robozonky.integrations.stonky.Util.getFile(Util.java:56)
	at com.github.robozonky.integrations.stonky.DriveOverview.createOrReuseStonky(DriveOverview.java:212)
	at com.github.robozonky.integrations.stonky.DriveOverview.latestStonky(DriveOverview.java:194)
	at com.github.robozonky.integrations.stonky.Stonky.lambda$run$2(Stonky.java:142)
	at com.github.robozonky.integrations.stonky.Util.lambda$wrap$1(Util.java:107)
	... 2 common frames omitted
```
[log.zip](https://github.com/RoboZonky/robozonky/files/2999057/log.zip)

**Comment by triceo** [comment]
Zdravím, dvě věci:

- Nějaký problém tam určitě bude.
- Nicméně `1aW_c-1nUXb4B8S5voxNTWhL982KRQJ6czRccDuPnzIoLtQhss` je neexistující Google soubor. Tohle už by mělo být opravené - Anthony uvedl špatný odkaz na aktuální verzi Stonky, a od té doby to opravil. Je to už pár dní, takže soudím, že je to buď ze staršího logu, nebo se z toho RoboZonky z nějakého důvodu nevzpamatoval.

Každopádně to bude potřeba prozkoumat.

**Comment by vvvlc** [comment]
Tak to muze byt ten duvod, o 17,18,19,20 nemam soubory na gdrive. viz obrazek
![image](https://user-images.githubusercontent.com/15854496/54869116-81d18000-4d94-11e9-92eb-212d7f493c7f.png)

**Comment by triceo** [comment]
@vvvlc Z toho, co vidím, soudím že tenhle report už můžu zavřít? Soubor se vytváří.

Co se intervalu čekání na stažení souborů ze Zonky týká, je nastavený na 30 minut. Obvykle to trvá jednotky minut. Zatím bych to neměnil, pokud se neukáže, že je to nějaký dlouhodobý problém.

**Comment by triceo** [comment]
Považuji za vyřešené, pokud se nedozvím nic dalšího.
