### ISSUE TITLE
Instalátor nefunguje na Javě 8

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#409]
Jak se zdá, Log4J z nějakého důvodu obsahuje jednu třídu, která byla zkompilovaná pro Javu 9. Co s tím, to zatím nevím.

    java.util.concurrent.ExecutionException: java.lang.UnsupportedClassVersionError: org/apache/logging/log4j/util/StackLocator has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_201]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206) ~[na:1.8.0_201]
	at com.github.robozonky.installer.AbstractValidator.validateData(AbstractValidator.java:43) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.installer.StrategySettingsValidator.validateData(StrategySettingsValidator.java:28) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:504) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:486) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanelView.validateData(AbstractPanelView.java:429) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.gui.IzPanelView.validateData(IzPanelView.java:114) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:259) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanelView.isValid(AbstractPanelView.java:234) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.gui.IzPanelView.isValid(IzPanelView.java:60) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanels.executeValidationActions(AbstractPanels.java:564) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanels.isValid(AbstractPanels.java:178) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.panel.AbstractPanels.next(AbstractPanels.java:228) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.gui.DefaultNavigator.next(DefaultNavigator.java:341) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.gui.DefaultNavigator.next(DefaultNavigator.java:326) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.gui.DefaultNavigator$NavigationHandler.navigate(DefaultNavigator.java:559) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.gui.DefaultNavigator$NavigationHandler.access$100(DefaultNavigator.java:522) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.izforge.izpack.installer.gui.DefaultNavigator$NavigationHandler$1$1.run(DefaultNavigator.java:542) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [na:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [na:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [na:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [na:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [na:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [na:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [na:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_201]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_201]
    Caused by: java.lang.UnsupportedClassVersionError: org/apache/logging/log4j/util/StackLocator has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_201]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_201]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_201]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_201]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_201]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_201]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[na:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_201]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_201]
	at org.apache.logging.log4j.util.StackLocatorUtil.<clinit>(StackLocatorUtil.java:28) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.api.remote.enums.Region.<clinit>(Region.java:54) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.regionExpression(NaturalLanguageStrategyParser.java:1630) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.regionCondition(NaturalLanguageStrategyParser.java:3676) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.primaryMarketplaceFilterCondition(NaturalLanguageStrategyParser.java:3321) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.primaryMarketplaceFilterConditions(NaturalLanguageStrategyParser.java:3031) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.primaryMarketplaceFilter(NaturalLanguageStrategyParser.java:2779) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.oldMarketplaceFilterExpression(NaturalLanguageStrategyParser.java:2317) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.marketplaceFilterExpression(NaturalLanguageStrategyParser.java:2231) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.complexExpression(NaturalLanguageStrategyParser.java:526) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyParser.primaryExpression(NaturalLanguageStrategyParser.java:342) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.SideEffectFreeParser.apply(SideEffectFreeParser.java:89) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyService.parseWithAntlr(NaturalLanguageStrategyService.java:62) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyService.lambda$parseOrCached$0(NaturalLanguageStrategyService.java:54) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_201]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyService.parseOrCached(NaturalLanguageStrategyService.java:52) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyService.getStrategy(NaturalLanguageStrategyService.java:74) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.strategy.natural.NaturalLanguageStrategyService.toInvest(NaturalLanguageStrategyService.java:88) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.common.extensions.StrategyLoader.processStrategyService(StrategyLoader.java:50) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.common.extensions.StrategyLoader.lambda$load$0(StrategyLoader.java:60) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_201]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[na:1.8.0_201]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_201]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_201]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_201]
	at com.github.robozonky.common.extensions.StrategyLoader.load(StrategyLoader.java:62) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.common.extensions.StrategyLoader.toInvest(StrategyLoader.java:67) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.cli.StrategyValidationFeature.test(StrategyValidationFeature.java:80) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.installer.StrategySettingsValidator.validateDataPossiblyThrowingException(StrategySettingsValidator.java:49) [robozonky-distribution-installer-5.1.0-full.jar:na]
	at com.github.robozonky.installer.AbstractValidator.lambda$validateData$0(AbstractValidator.java:41) ~[robozonky-distribution-installer-5.1.0-full.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Finished validation.

**Comment by triceo** [comment]
Zjištění:

- `StackLocator` je v `log4j-api` modulu.
- `log4j-api` je multi-release JAR a zrovna `StackLocator` má jinou verzi pro Javu 9 a novější resp. jinou pro starší Javy.

A teď je potřeba zjistit, proč si v případě IZPack instalátoru vybere zrovna tu blbou.

**Comment by triceo** [comment]
Problém odhalen: pro instalátor nejdřív postavíme `jar-with-dependencies`. A protože jsme buildovali na Javě 11, `maven-assembly-plugin` neudělal multi-release JAR a zároveň neměl důvod použít starší verzi. Takže výsledkem je instalátor, který je zkompilovaný pro Javu 11, i když vůbec není.

No a teď co s tím...

**Comment by triceo** [comment]
Stačí aktualizovat `maven-assembly-plugin` na verzi 3.1.1. Ta sice v changelogu nic takového nemá, ale zato aktualizuje hromadu další závislostí, které asi ten problém vyřešily.
