### ISSUE TITLE
Podivné NPE během vyhodnocování strategie

### ISSUE THREAD

**Issue by triceo** [RoboZonky/robozonky#433]
Např. tahle:

    java.lang.NullPointerException
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.conditions.RangeCondition.toBigDecimal(RangeCondition.java:29)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.conditions.RangeCondition.test(RangeCondition.java:51)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.conditions.AbstractRangeCondition.test(AbstractRangeCondition.java:41)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.conditions.RevenueRateCondition.test(RevenueRateCondition.java:23)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.conditions.MarketplaceFilter.lambda$test$0(MarketplaceFilter.java:91)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.allMatch(Unknown Source)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.conditions.MarketplaceFilter.test(MarketplaceFilter.java:92)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.ParsedStrategy.lambda$matchesFilter$0(ParsedStrategy.java:90)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.ParsedStrategy.matchesFilter(ParsedStrategy.java:92)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.ParsedStrategy.lambda$getApplicableParticipations$5(ParsedStrategy.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.Util.sortByRating(Util.java:48)
	at com.github.robozonky.strategy.natural/com.github.robozonky.strategy.natural.NaturalLanguagePurchaseStrategy.recommend(NaturalLanguagePurchaseStrategy.java:87)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.PurchasingSession.purchase(PurchasingSession.java:90)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.PurchasingSession.purchase(PurchasingSession.java:78)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.StrategyExecutor.invest(StrategyExecutor.java:101)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.StrategyExecutor.actuallyGet(StrategyExecutor.java:119)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.StrategyExecutor.get(StrategyExecutor.java:131)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.Skippable.run(Skippable.java:65)
	at com.github.robozonky.common/com.github.robozonky.common.async.TaskDescriptor.lambda$submit$1(TaskDescriptor.java:94)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Chybí `Loan` instance ve `Wrapper`u, ale ona chybět nemůže, protože se předtím načítá z cache - a pokud v ní není, tak se stáhne naživo.

**Comment by triceo** [comment]
Kromě toho se to stává jen malému množství lidí, zatím si stěžovali dva. Ale touhle oblastí kódu prochází všichni uživatelé robota, mnohokrát za minutu.

**Comment by triceo** [comment]
Zonky u *některých* půjček neposílá atribute `revenueRate`, resp. je `null`. To vysvětluje, proč to vidí jen někteří uživatelé. Protože jen někdo používá filtr podle revenue rate, a zároveň protože se to nevztahuje ani na všechny půjčky.

Co se týká řešení, diskutuji o tom se Zonky vývojáři.

**Comment by triceo** [comment]
Revenue rate skutečně posílají jen ve velmi specifických podmínkách. Ve všech ostatních ho tedy robot bude muset odhadnout z aktuální velikosti portfolia, což se naštěstí dá udělat velmi přesně.
