### ISSUE TITLE
Verze 5.2.4 vyžaduje novější JRE

### ISSUE THREAD

**Issue by adambisek** [RoboZonky/robozonky#439]
Zdravím,
díky BC breaku Zonky API jsem byl nucen udělat upgrade Robozonky (a díky za něj!).
Problém je, že evidentně vyžaduje novější JRE:
```
java -jar robozonky-distribution-installer-5.2.4-full.jar
Command line arguments:
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/robozonky/installer/RoboZonkyInstallerListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.izforge.izpack.core.container.AbstractContainer.getClass(AbstractContainer.java:261)
	at com.izforge.izpack.core.factory.DefaultObjectFactory.create(DefaultObjectFactory.java:101)
	at com.izforge.izpack.installer.container.impl.CustomDataLoader.addInstallerListener(CustomDataLoader.java:139)
	at com.izforge.izpack.installer.container.impl.CustomDataLoader.loadCustomData(CustomDataLoader.java:114)
	at com.izforge.izpack.installer.container.impl.InstallerContainer.resolveComponents(InstallerContainer.java:147)
	at com.izforge.izpack.installer.container.impl.InstallerContainer.fillContainer(InstallerContainer.java:80)
	at com.izforge.izpack.core.container.AbstractContainer.initialise(AbstractContainer.java:304)
	at com.izforge.izpack.core.container.AbstractContainer.initialise(AbstractContainer.java:284)
	at com.izforge.izpack.installer.container.impl.ConsoleInstallerContainer.<init>(ConsoleInstallerContainer.java:52)
	at com.izforge.izpack.installer.bootstrap.InstallerConsole.run(InstallerConsole.java:47)
	at com.izforge.izpack.installer.bootstrap.Installer.launchInstall(Installer.java:302)
	at com.izforge.izpack.installer.bootstrap.Installer.start(Installer.java:238)
	at com.izforge.izpack.installer.bootstrap.Installer.main(Installer.java:78)
```

Bylo by prosím možné ještě zpětně podporovat starší JRE? 🙏 🙏 🙏 

---

Zkoušel jsem to samozřejmě sám vyřešit, problém je ale, že třeba na raspbianu nejsem schopen update udělat.  Třeba podle [tohoto guide](https://gist.github.com/ribasco/fff7d30b31807eb02b32bcf35164f11f) mi to bohužel vyhučí ve 4. kroku na:
```
$ sudo apt-get install oracle-java8-installer
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate
```

**Comment by mark-stopka** [comment]
OpenJDK? Docker?
--
Best regards / S pozdravem,
Mark Stopka

mobile: +420 704 373 561

**Comment by adambisek** [comment]
Bez dockeru, přímo na zeleze.

java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

Doufam, ze je to odpověď na tvou otázku, v Jave se nevyznám.

**Comment by triceo** [comment]
Bohužel, minimální podporovaná verze JRE je 11, a to od RoboZonky 5.2.0.
Upozorňoval jsem na tuhle změnu již od verze 5.0.0.
Není cesty zpět.

**Comment by triceo** [comment]
Trochu jsem pogooglil, jak dostat Javu 11 na Raspbian, a možností je hned několik. 

Debian má i oficiální balíčky pro ARM:
https://packages.debian.org/stretch-backports/openjdk-11-jre

**Comment by adambisek** [comment]
## Guide pro ostatní, kdyby to někdo taky řešil:


This is a very short post on what I ended up doing to get an OpenJDK 11 build for Raspbian on my Raspberry Pi 3.


#### 1) Get the latest JDK 11 build of the Liberica JVM (Debian package for ARM v7 & v8, provided by Bell Soft)
The java download page is here https://www.bell-sw.com/java.html.

For example:
```
wget https://github.com/bell-sw/Liberica/releases/download/11.0.2/bellsoft-jdk11.0.2-linux-arm32-vfp-hflt.deb
```

#### 2) Install it
```
sudo apt-get install ./bellsoft-jdk11.0.2-linux-arm32-vfp-hflt.deb
```

#### 3) Set the defaults (if you want to - optional)
```
sudo update-alternatives --config javac
sudo update-alternatives --config java
```
