### ISSUE TITLE
Token retrieval failed

### ISSUE THREAD

**Issue by samurajj** [RoboZonky/robozonky#443]
Ahoj,
posílám 2 mail reporty co mi přišly (mezi dalšími tucty podobnými), snad Vám pomůže udělat robota ještě lepšího ;)

Robot vždy chvíli běží a do pár dní se něco zvrtne a pak už chodí jen chyby. Většinou se stačí přihlásit do zonky a robot se sám vzpamatuje. Řekl bych, že vše souvisí s přihlašováním na Zonky a expirací tokenu. Ale kdyby to omezení pocházelo jen od Zonky a věděli jste o něm, nespamoval by robot náhodnými vyjímkami, ale napsal by "díky omezení na straně Zonky se musíš přihlásit...". 
Teď jsem si ještě na Zonky při přihlašování všiml nového textíku "Počet neúspěšných přihlášení je podezdřele vysoký. Přihlášení nyní vyžaduje kontrolu, že jste člověk (tzv. CAPTCHA). Prosím, zkuste to ještě jednou." => Tedy napadlo mě, jestli spouštěč tohoto procesu není nějaká jiná chybka někde v robotovi... (a nebo se nějaký úplně jiný robot snaží dostat do mého účtu?) .... mno proto se tak rozepisuju, jestli máte někdo podobný problém, nebo nápad co zkusit, abych se nemusel každých pár dní ručně přihlašovat na Zonky.

javax.ws.rs.ProcessingException: java.lang.IllegalStateException: Token retrieval failed.
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:599)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:436)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:148)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy73.items(Unknown Source)
	at com.github.robozonky.common/com.github.robozonky.common.remote.Api.call(Api.java:41)
	at com.github.robozonky.common/com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:66)
	at com.github.robozonky.common/com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:61)
	at com.github.robozonky.common/com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:79)
	at com.github.robozonky.common/com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:71)
	at com.github.robozonky.common/com.github.robozonky.common.remote.EntityCollectionPageSource.fetch(EntityCollectionPageSource.java:49)
	at paging.streams@0.8/com.github.rutledgepaulv.pagingstreams.PagingStreams$SpliteratorBuilder.build(PagingStreams.java:88)
	at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:405)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.robozonky.app/com.github.robozonky.app.transactions.IncomeProcessor.processNewTransactions(IncomeProcessor.java:50)
	at com.github.robozonky.app/com.github.robozonky.app.transactions.IncomeProcessor.run(IncomeProcessor.java:72)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.PowerTenant.inTransaction(PowerTenant.java:52)
	at com.github.robozonky.app/com.github.robozonky.app.transactions.IncomeProcessor.accept(IncomeProcessor.java:79)
	at com.github.robozonky.app/com.github.robozonky.app.transactions.IncomeProcessor.accept(IncomeProcessor.java:33)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.DaemonInvestmentMode.lambda$scheduleJobs$2(DaemonInvestmentMode.java:96)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.Skippable.run(Skippable.java:65)
	at com.github.robozonky.common/com.github.robozonky.common.async.TaskDescriptor.lambda$submit$1(TaskDescriptor.java:94)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalStateException: Token retrieval failed.
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.lambda$get$2(ZonkyApiTokenSupplier.java:110)
	at io.vavr@0.10.0/io.vavr.control.Either.getOrElseThrow(Either.java:342)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:110)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:36)
	at com.github.robozonky.common/com.github.robozonky.common.remote.AuthenticatedFilter.filter(AuthenticatedFilter.java:36)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:586)
	... 27 more
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:215)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:191)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy57.login(Unknown Source)
	at com.github.robozonky.common/com.github.robozonky.common.remote.OAuth.lambda$login$0(OAuth.java:36)
	at com.github.robozonky.common/com.github.robozonky.common.remote.Api.call(Api.java:41)
	at com.github.robozonky.common/com.github.robozonky.common.remote.Api.call(Api.java:49)
	at com.github.robozonky.common/com.github.robozonky.common.remote.OAuth.login(OAuth.java:36)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.lambda$login$0(ZonkyApiTokenSupplier.java:72)
	at com.github.robozonky.common/com.github.robozonky.common.remote.ApiProvider.oauth(ApiProvider.java:106)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.login(ZonkyApiTokenSupplier.java:69)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.actuallyRefreshOrLogin(ZonkyApiTokenSupplier.java:84)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.refreshOrLogin(ZonkyApiTokenSupplier.java:96)
	at com.github.robozonky.common/com.github.robozonky.common.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:50)
	at com.github.robozonky.common/com.github.robozonky.common.async.ReloadableImpl.lambda$get$0(ReloadableImpl.java:49)
	at io.vavr@0.10.0/io.vavr.control.Try.of(Try.java:75)
	at io.vavr@0.10.0/io.vavr.control.Try.ofSupplier(Try.java:92)
	at com.github.robozonky.common/com.github.robozonky.common.async.ReloadableImpl.get(ReloadableImpl.java:49)
	... 31 more

Vygeneroval RoboZonky/5.2.7 (http://www.robozonky.cz) pro Zonky účet z...l@e...z v čase 2019-07-19T17:31:03.23+02:00 na základě systémové události vytvořené v čase 2019-07-19T17:31:01.941+02:00.

=================================================================

java.lang.IllegalStateException: Failed fetching remote portfolio.
	at com.github.robozonky.app/com.github.robozonky.app.tenant.RemotePortfolioImpl.lambda$getRemotePortfolio$8(RemotePortfolioImpl.java:170)
	at io.vavr@0.10.0/io.vavr.control.Either.getOrElseThrow(Either.java:342)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.RemotePortfolioImpl.getRemotePortfolio(RemotePortfolioImpl.java:170)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.RemotePortfolioImpl.getBalance(RemotePortfolioImpl.java:175)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.StrategyExecutor.actuallyGet(StrategyExecutor.java:112)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.StrategyExecutor.get(StrategyExecutor.java:131)
	at com.github.robozonky.app/com.github.robozonky.app.daemon.Skippable.run(Skippable.java:65)
	at com.github.robozonky.common/com.github.robozonky.common.async.TaskDescriptor.lambda$submit$1(TaskDescriptor.java:94)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: javax.ws.rs.ProcessingException: java.lang.IllegalStateException: Token retrieval failed.
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:599)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:436)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:148)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy69.item(Unknown Source)
	at com.github.robozonky.common/com.github.robozonky.common.remote.Api.call(Api.java:41)
	at com.github.robozonky.common/com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:66)
	at com.github.robozonky.common/com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:61)
	at com.github.robozonky.common/com.github.robozonky.common.remote.PaginatedApi.execute(PaginatedApi.java:56)
	at com.github.robozonky.common/com.github.robozonky.common.remote.Zonky.getStatistics(Zonky.java:306)
	at com.github.robozonky.common/com.github.robozonky.common.remote.ApiProvider.call(ApiProvider.java:131)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.PowerTenantImpl.call(PowerTenantImpl.java:93)
	at com.github.robozonky.common/com.github.robozonky.common.tenant.Tenant.call(Tenant.java:50)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.RemoteData.load(RemoteData.java:50)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.RemotePortfolioImpl.lambda$new$0(RemotePortfolioImpl.java:62)
	at com.github.robozonky.common/com.github.robozonky.common.async.ReloadableBuilder.lambda$build$3(ReloadableBuilder.java:127)
	at com.github.robozonky.common/com.github.robozonky.common.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:50)
	at com.github.robozonky.common/com.github.robozonky.common.async.ReloadableImpl.lambda$get$0(ReloadableImpl.java:49)
	at io.vavr@0.10.0/io.vavr.control.Try.of(Try.java:75)
	at io.vavr@0.10.0/io.vavr.control.Try.ofSupplier(Try.java:92)
	at com.github.robozonky.common/com.github.robozonky.common.async.ReloadableImpl.get(ReloadableImpl.java:49)
	... 10 more
Caused by: java.lang.IllegalStateException: Token retrieval failed.
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.lambda$get$2(ZonkyApiTokenSupplier.java:110)
	at io.vavr@0.10.0/io.vavr.control.Either.getOrElseThrow(Either.java:342)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:110)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:36)
	at com.github.robozonky.common/com.github.robozonky.common.remote.AuthenticatedFilter.filter(AuthenticatedFilter.java:36)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:586)
	... 31 more
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:215)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:191)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:150)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at resteasy.client@3.6.3.Final/org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy57.login(Unknown Source)
	at com.github.robozonky.common/com.github.robozonky.common.remote.OAuth.lambda$login$0(OAuth.java:36)
	at com.github.robozonky.common/com.github.robozonky.common.remote.Api.call(Api.java:41)
	at com.github.robozonky.common/com.github.robozonky.common.remote.Api.call(Api.java:49)
	at com.github.robozonky.common/com.github.robozonky.common.remote.OAuth.login(OAuth.java:36)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.lambda$login$0(ZonkyApiTokenSupplier.java:72)
	at com.github.robozonky.common/com.github.robozonky.common.remote.ApiProvider.oauth(ApiProvider.java:106)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.login(ZonkyApiTokenSupplier.java:69)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.actuallyRefreshOrLogin(ZonkyApiTokenSupplier.java:84)
	at com.github.robozonky.app/com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.refreshOrLogin(ZonkyApiTokenSupplier.java:96)
	at com.github.robozonky.common/com.github.robozonky.common.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:50)
	at com.github.robozonky.common/com.github.robozonky.common.async.ReloadableImpl.lambda$get$0(ReloadableImpl.java:49)
	at io.vavr@0.10.0/io.vavr.control.Try.of(Try.java:75)
	at io.vavr@0.10.0/io.vavr.control.Try.ofSupplier(Try.java:92)
	at com.github.robozonky.common/com.github.robozonky.common.async.ReloadableImpl.get(ReloadableImpl.java:49)
	... 35 more

Vygeneroval RoboZonky/5.2.7 (http://www.robozonky.cz) pro Zonky účet z...l@e...z v čase 2019-07-18T18:32:45.193+02:00 na základě systémové události vytvořené v čase 2019-07-18T18:32:40.892+02:00.

**Comment by triceo** [comment]
Problém je, že ve chvíli, kdy se na webu objeví CAPTCHA, je robot k ničemu - ta CAPTCHA se musí ručně vyplnit, a pak zase přihlášení začne fungovat. 

Nevím, na základě čeho se CAPTCHA objeví, ale občas se to stane. A v tuhle chvíli ani nevím, jak zjistit, jestli je na webu CAPTCHA. Nicméně po dobu, co je na webu CAPTCHA, se robotu nikdy nepodaří přihlásit. A Zonky to dost možná bere za to "neúspěšné přihlášení" a stěžuje si, že je jich vysoký počet.

Takže je to takový začarovaný kruh. Jedna CAPTCHA vzniklá mimo robota vytvoří další CAPTCHA, kterou už zavinil robot.

V tuhle chvíli s tím jednak nemám co udělat, druhak by to bylo zbytečné. Autentizace se na Zonky bude velmi brzy zásadně měnit, a robota pak kvůli tomu bude potřeba přeimplementovat.

**Comment by samurajj** [comment]
Díky za vysvětlení. Počkám co přinesou změny.
