### ISSUE TITLE
Nefungují notifikace o příhozu

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#496]
log:  
```
11:22:56.218 INFO  Invested 200.00 CZK into loan #638165.
11:22:57.743 WARN  Listener class com.github.robozonky.notifications.listeners.InvestmentMadeEventListener failed for LazyEventImpl{eventType=interface com.github.robozonky.api.notifications.InvestmentMadeEvent}.
java.lang.IllegalStateException: Event processing failed.
        at com.github.robozonky.notifications.listeners.AbstractListener.handle(AbstractListener.java:163) ~[robozonky-notifications-5.6.0.jar:?]
        at com.github.robozonky.app.events.SessionEvents.fireAny(SessionEvents.java:112) ~[robozonky-app-5.6.0.jar:?]
        at com.github.robozonky.app.events.SessionEvents$EventTriggerRunnable.run(SessionEvents.java:183) ~[robozonky-app-5.6.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1799) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.seznam.cz:465
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469) ~[commons-email-1.5.jar:?]
        at org.apache.commons.mail.Email.send(Email.java:1496) ~[commons-email-1.5.jar:?]
        at com.github.robozonky.notifications.EmailHandler.send(EmailHandler.java:99) ~[robozonky-notifications-5.6.0.jar:?]
        at com.github.robozonky.notifications.AbstractTargetHandler.offer(AbstractTargetHandler.java:135) ~[robozonky-notifications-5.6.0.jar:?]
        at com.github.robozonky.notifications.listeners.AbstractListener.handle(AbstractListener.java:160) ~[robozonky-notifications-5.6.0.jar:?]
        ... 9 more
Caused by: javax.mail.AuthenticationFailedException: 535 5.7.1 Incorrect authentication data. Two Factor authentificatoin failed. SMTP Client password is not set.

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:947) ~[jakarta.mail-1.6.4.jar:?]
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858) ~[jakarta.mail-1.6.4.jar:?]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762) ~[jakarta.mail-1.6.4.jar:?]
        at javax.mail.Service.connect(Service.java:364) ~[jakarta.mail-1.6.4.jar:?]
        at javax.mail.Service.connect(Service.java:222) ~[jakarta.mail-1.6.4.jar:?]
        at javax.mail.Service.connect(Service.java:171) ~[jakarta.mail-1.6.4.jar:?]
        at javax.mail.Transport.send0(Transport.java:230) ~[jakarta.mail-1.6.4.jar:?]
        at javax.mail.Transport.send(Transport.java:100) ~[jakarta.mail-1.6.4.jar:?]
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459) ~[commons-email-1.5.jar:?]
        at org.apache.commons.mail.Email.send(Email.java:1496) ~[commons-email-1.5.jar:?]
        at com.github.robozonky.notifications.EmailHandler.send(EmailHandler.java:99) ~[robozonky-notifications-5.6.0.jar:?]
        at com.github.robozonky.notifications.AbstractTargetHandler.offer(AbstractTargetHandler.java:135) ~[robozonky-notifications-5.6.0.jar:?]
        at com.github.robozonky.notifications.listeners.AbstractListener.handle(AbstractListener.java:160) ~[robozonky-notifications-5.6.0.jar:?]
        ... 9 more
```

**Comment by panther7** [comment]
Aha, už vím, mám jiné heslo do emailu... Takže by ta chyba mohla být lépe userfriendly čitelná :)

**Comment by panther7** [comment]
Už to vidím,
```
Incorrect authentication data. Two Factor authentificatoin failed. SMTP Client password is not set.
```

Tak to pak můžete zavřít, díky :)

Jinak by byůp hezké, dkyby heslo k emailu nebylo v plaintextu v notification.cfg

**Comment by triceo** [comment]
Díky, zavírám. Co se hesla k e-mailu týká, máte pravdu, ale zatím se mi to nepodařilo vymyslet.
GMail mi to trochu ulehčuje tím, že nepoužívá hesla, ale "jednorázové" tokeny - nicméně ani to není ideální.
