### ISSUE TITLE
Poslední dobou mi nejde spustit robozonky

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#544]
![Image-2020-07-13 11 16 34](https://user-images.githubusercontent.com/3808250/87287378-5418c900-c4fa-11ea-811d-f8baaaa6315a.png)

```
11:14:22.433 INFO  [main] com.github.robozonky.app.RoboZonkyStartupNotifier - 
################################################################################
#        ____            __          _____                   __                #
#       / __ \  ____    / /_   ____ /__  /  ____    ____    / /__   __  __     #
#      / /_/ / / __ \  / __ \ / __ \  / /  / __ \  / __ \  / //_/  / / / /     #
#     / _, _/ / /_/ / / /_/ // /_/ / / /__/ /_/ / / / / / / ,<    / /_/ /      #
#    /_/ |_|  \____/ /_.___/ \____/ /____/\____/ /_/ /_/ /_/|_|   \__, /       #
#                                              v6.0.0 'Unnamed'  /____/        #
#                                                                              #
################################################################################
11:14:22.433 DEBUG [main] com.github.robozonky.app.RoboZonkyStartupNotifier - Running AdoptOpenJDK OpenJDK 64-Bit Server VM v14.0.1+7 from C:\Program Files\AdoptOpenJDK\jre-14.0.1.7-hotspot.
11:14:22.433 DEBUG [main] com.github.robozonky.app.RoboZonkyStartupNotifier - Running on Windows 10 v10.0 (amd64, 12 CPUs, cs_CZ, UTF-8).
11:14:22.433 DEBUG [main] com.github.robozonky.app.RoboZonkyStartupNotifier - Current working directory is 'C:\Users\filip.mosner\Documents\RoboZonky'.
11:14:22.433 DEBUG [main] com.github.robozonky.app.events.GlobalEvents - Firing LazyEventImpl{eventType=class com.github.robozonky.app.events.impl.RoboZonkyInitializedEventImpl} for all sessions.
11:14:22.433 DEBUG [main] com.github.robozonky.internal.extensions.ListenerServiceLoader - Loading listeners for interface com.github.robozonky.api.notifications.RoboZonkyInitializedEvent.
11:14:22.433 DEBUG [main] com.github.robozonky.internal.extensions.ListenerServiceLoader - Processing 'class com.github.robozonky.notifications.NotificationListenerService'.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Scheduling simple batch jobs.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.extensions.ExtensionsManager - Retrieving service loader for 'interface com.github.robozonky.internal.jobs.JobService'.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.extensions.ExtensionsManager - Extensions folder not found.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.extensions.JobServiceLoader - Looking up batch jobs.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.version.VersionDetectionJob to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT24H, starting in PT0S. Optional timeout of PT1M.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@16423501 every 86400000000000 ns, starting in 0 ns.
11:14:22.440 DEBUG [pool-2-thread-1] com.github.robozonky.internal.async.TaskDescriptor - Submitting com.github.robozonky.internal.async.TaskDescriptor@16423501 for actual execution.
11:14:22.440 DEBUG [pool-2-thread-1] com.github.robozonky.internal.async.TaskDescriptor - Will be killed in 60000000000 ns.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Scheduling tenant-based batch jobs.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.extensions.JobServiceLoader - Looking up batch jobs.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.daemon.SellingJob to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT2H, starting in PT12M16S. Optional timeout of PT30M.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@6db66836 every 7200000000000 ns, starting in 736000000000 ns.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.daemon.ReservationsPreferencesJob to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT1H, starting in PT1H. Optional timeout of PT1M.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@db44aa2 every 3600000000000 ns, starting in 3600000000000 ns.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.daemon.ReservationsProcessingJob to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT4H, starting in PT2H. Optional timeout of PT1M.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@2de366bb every 14400000000000 ns, starting in 7200000000000 ns.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.delinquencies.DelinquencyNotificationJob to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT12H, starting in PT14M18S. Optional timeout of PT10M.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@3f093abe every 43200000000000 ns, starting in 858000000000 ns.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.summaries.SummarizerJob to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT168H, starting in PT138H41M37.5598881S. Optional timeout of PT1H.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@4eeea57d every 604800000000000 ns, starting in 499297559888100 ns.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.daemon.SaleCheckJob to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT1H, starting in PT3M40S. Optional timeout of PT1M.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@780ec4a5 every 3600000000000 ns, starting in 220000000000 ns.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Job scheduling over.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Scheduling daemon threads.
11:14:22.440 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.daemon.InvestingSession to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT1S, starting in PT0S. Optional timeout of PT0S.
11:14:22.440 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@532721fd every 1000000000 ns, starting in 0 ns.
11:14:22.440 DEBUG [pool-2-thread-1] com.github.robozonky.internal.async.TaskDescriptor - Submitting com.github.robozonky.internal.async.TaskDescriptor@532721fd for actual execution.
11:14:22.456 DEBUG [main] com.github.robozonky.app.daemon.Daemon - Submitting class com.github.robozonky.app.daemon.PurchasingSession to com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler@25f9407e, repeating after PT1S, starting in PT0.25S. Optional timeout of PT0S.
11:14:22.456 DEBUG [main] com.github.robozonky.internal.async.CachedThreadPoolBasedScheduler - Scheduling com.github.robozonky.internal.async.TaskDescriptor@2e185cd7 every 1000000000 ns, starting in 250000000 ns.
11:14:22.457 DEBUG [main] com.github.robozonky.app.runtime.Lifecycle - Pausing main thread.
11:14:22.457 DEBUG [pool-2-thread-3] com.github.robozonky.internal.remote.ApiProvider - Creating a new authenticated API for com.github.robozonky.app.tenant.ZonkyApiTokenSupplier@533cee40.
11:14:22.457 DEBUG [pool-2-thread-3] com.github.robozonky.internal.remote.ProxyFactory - Creating RESTEasy client.
11:14:22.457 DEBUG [pool-2-thread-3] com.github.robozonky.internal.remote.ProxyFactory - Set socket timeout to 10000 ms.
11:14:22.457 DEBUG [pool-2-thread-3] com.github.robozonky.internal.remote.ProxyFactory - Set connection timeout to 10000 ms.
11:14:22.718 DEBUG [pool-2-thread-1] com.github.robozonky.internal.async.TaskDescriptor - Submitting com.github.robozonky.internal.async.TaskDescriptor@2e185cd7 for actual execution.
11:14:22.839 DEBUG [pool-2-thread-3] com.github.robozonky.app.tenant.ZonkyApiTokenSupplier - Current token ZonkyApiTokenImpl[id=0, type='bearer', expiresIn=86399, obtainedOn=2020-07-13T11:14:22.835757500+02:00, scope='SCOPE_INVESTMENT_READ SCOPE_RESERVATIONS_WRITE SCOPE_INVESTMENT_WRITE SCOPE_RESERVATIONS_READ SCOPE_RESERVATIONS_SETTINGS_WRITE SCOPE_NOTIFICATIONS_WRITE SCOPE_APP_BASIC_INFO SCOPE_RESERVATIONS_SETTINGS_READ SCOPE_NOTIFICATIONS_READ'] expiring on 2020-07-14T11:14:21.835757500+02:00.
11:14:23.072 DEBUG [pool-2-thread-3] com.github.robozonky.internal.remote.AuthenticationFilter - HTTP POST Response from https://api.zonky.cz/oauth/token: 400 Bad Request.
11:14:23.072 DEBUG [pool-2-thread-3] com.github.robozonky.internal.remote.AuthenticationFilter - Response body is: {"error":"invalid_grant","error_description":"Invalid refresh token: 1e82c374-8375-4c93-ba41-b2fd05acec70"}
11:14:23.076 DEBUG [pool-2-thread-3] com.github.robozonky.app.tenant.AvailabilityImpl - Fault identified, forcing pause.
java.lang.IllegalStateException: Failed retrieving restrictions.
	at com.github.robozonky.internal.SessionInfoImpl.lambda$getRestrictions$2(SessionInfoImpl.java:85) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.util.functional.Either.lambda$getOrElseThrow$0(Either.java:54) ~[robozonky-app-6.0.0-full.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at com.github.robozonky.internal.util.functional.Either.getOrElseThrow(Either.java:54) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.SessionInfoImpl.getRestrictions(SessionInfoImpl.java:85) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.SessionInfoImpl.canInvest(SessionInfoImpl.java:90) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.daemon.InvestingOperationDescriptor.isEnabled(InvestingOperationDescriptor.java:39) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.daemon.StrategyExecutor.get(StrategyExecutor.java:112) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.daemon.Skippable.run(Skippable.java:74) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.TaskDescriptor.lambda$new$0(TaskDescriptor.java:48) ~[robozonky-app-6.0.0-full.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: javax.ws.rs.ProcessingException: Operation failed and can not be retried.
	at com.github.robozonky.internal.remote.Api.call(Api.java:64) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:82) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:86) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Zonky.getRestrictions(Zonky.java:258) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.ApiProvider.call(ApiProvider.java:137) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.PowerTenantImpl.call(PowerTenantImpl.java:85) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.PowerTenantImpl.lambda$new$5(PowerTenantImpl.java:73) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:57) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.ReloadableImpl.get(ReloadableImpl.java:51) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.SessionInfoImpl.getRestrictions(SessionInfoImpl.java:84) ~[robozonky-app-6.0.0-full.jar:?]
	... 9 more
Caused by: javax.ws.rs.ProcessingException: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:696) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:485) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[robozonky-app-6.0.0-full.jar:?]
	at com.sun.proxy.$Proxy38.restrictions(Unknown Source) ~[?:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:61) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:82) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:86) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Zonky.getRestrictions(Zonky.java:258) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.ApiProvider.call(ApiProvider.java:137) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.PowerTenantImpl.call(PowerTenantImpl.java:85) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.PowerTenantImpl.lambda$new$5(PowerTenantImpl.java:73) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:57) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.ReloadableImpl.get(ReloadableImpl.java:51) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.SessionInfoImpl.getRestrictions(SessionInfoImpl.java:84) ~[robozonky-app-6.0.0-full.jar:?]
	... 9 more
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:258) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:234) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:62) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:151) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[robozonky-app-6.0.0-full.jar:?]
	at com.sun.proxy.$Proxy46.refresh(Unknown Source) ~[?:?]
	at com.github.robozonky.internal.remote.OAuth.lambda$refresh$1(OAuth.java:41) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:61) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:82) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:86) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.OAuth.refresh(OAuth.java:41) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.lambda$refreshOrFail$1(ZonkyApiTokenSupplier.java:98) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.ApiProvider.oauth(ApiProvider.java:122) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.refreshOrFail(ZonkyApiTokenSupplier.java:98) ~[robozonky-app-6.0.0-full.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.refreshOrFail(ZonkyApiTokenSupplier.java:88) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:57) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.ReloadableImpl.get(ReloadableImpl.java:51) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:114) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.ZonkyApiTokenSupplier.get(ZonkyApiTokenSupplier.java:39) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.AuthenticatedFilter.filter(AuthenticatedFilter.java:37) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:683) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:485) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112) ~[robozonky-app-6.0.0-full.jar:?]
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[robozonky-app-6.0.0-full.jar:?]
	at com.sun.proxy.$Proxy38.restrictions(Unknown Source) ~[?:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:61) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:82) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Api.call(Api.java:86) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.Zonky.getRestrictions(Zonky.java:258) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.remote.ApiProvider.call(ApiProvider.java:137) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.PowerTenantImpl.call(PowerTenantImpl.java:85) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.app.tenant.PowerTenantImpl.lambda$new$5(PowerTenantImpl.java:73) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:57) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.async.ReloadableImpl.get(ReloadableImpl.java:51) ~[robozonky-app-6.0.0-full.jar:?]
	at com.github.robozonky.internal.SessionInfoImpl.getRestrictions(SessionInfoImpl.java:84) ~[robozonky-app-6.0.0-full.jar:?]
	... 9 more
11:14:23.076 WARN  [pool-2-thread-3] com.github.robozonky.app.tenant.AvailabilityImpl - Forcing a pause due to a remote failure.
11:14:23.077 DEBUG [pool-2-thread-3] com.github.robozonky.app.daemon.Skippable - Unavailability starting.
11:14:23.077 DEBUG [pool-2-thread-3] com.github.robozonky.internal.extensions.ListenerServiceLoader - Loading listeners for interface com.github.robozonky.api.notifications.RoboZonkyDaemonSuspendedEvent.
11:14:23.077 DEBUG [pool-2-thread-3] com.github.robozonky.internal.extensions.ListenerServiceLoader - Processing 'class com.github.robozonky.notifications.NotificationListenerService'.
11:14:23.079 DEBUG [pool-2-thread-3] com.github.robozonky.notifications.NotificationEventListenerSupplier - DAEMON_SUSPENDED notification enabled for 'EMAIL'.
11:14:23.079 DEBUG [ForkJoinPool.commonPool-worker-19] com.github.robozonky.app.events.SessionEvents - Starting event 0 (LazyEventImpl{eventType=class com.github.robozonky.app.events.impl.RoboZonkyDaemonSuspendedEventImpl}).
11:14:23.079 DEBUG [ForkJoinPool.commonPool-worker-19] com.github.robozonky.notifications.listeners.RoboZonkyDaemonSuspendedEventListener - Notifying RoboZonkyDaemonSuspendedEventImpl[super=AbstractEventImpl[conceptionDateTime=2020-07-13T11:14:23.077682300+02:00, creationDateTime=2020-07-13T11:14:23.077682300+02:00], cause=java.lang.IllegalStateException: Failed retrieving restrictions.].
11:14:23.079 DEBUG [ForkJoinPool.commonPool-worker-19] com.github.robozonky.notifications.Counter - Loaded timestamps: [].
11:14:23.079 DEBUG [ForkJoinPool.commonPool-worker-19] com.github.robozonky.internal.async.ReloadableImpl - Reloaded com.github.robozonky.internal.async.ReloadableImpl@6833ec3b, new value is [].
11:14:23.172 DEBUG [pool-2-thread-4] com.github.robozonky.app.tenant.ZonkyApiTokenSupplier - Current token ZonkyApiTokenImpl[id=1, type='bearer', expiresIn=86399, obtainedOn=2020-07-13T11:14:23.172119700+02:00, scope='SCOPE_INVESTMENT_READ SCOPE_RESERVATIONS_WRITE SCOPE_INVESTMENT_WRITE SCOPE_RESERVATIONS_READ SCOPE_RESERVATIONS_SETTINGS_WRITE SCOPE_NOTIFICATIONS_WRITE SCOPE_APP_BASIC_INFO SCOPE_RESERVATIONS_SETTINGS_READ SCOPE_NOTIFICATIONS_READ'] expiring on 2020-07-14T11:14:22.172119700+02:00.
11:14:23.187 DEBUG [pool-2-thread-4] com.github.robozonky.internal.remote.AuthenticationFilter - HTTP POST Response from https://api.zonky.cz/oauth/token: 400 Bad Request.
11:14:23.187 DEBUG [pool-2-thread-4] com.github.robozonky.internal.remote.AuthenticationFilter - Response body is: {"error":"invalid_grant","error_description":"Invalid refresh token: 1e82c374-8375-4c93-ba41-b2fd05acec70"}
11:14:23.187 DEBUG [pool-2-thread-4] com.github.robozonky.app.tenant.AvailabilityImpl - Forced pause in effect since 2020-07-13T09:14:23.076185200Z, 1 failed retries.
```

**Comment by panther7** [comment]
Tak to bylo neplatným tokenem, tudíž by to chtělo lepší chybovou hlášku v konzoli a případné možnost pro rychlé a snadné obnovení. Díky :)

**Comment by triceo** [comment]
Jo, tohle je tokenem. Těžko se to detekuje, takže s lepší chybovou hláškou to není jednoduché. Každopádně nejrychlejší token refresh je přes CLI, viz https://github.com/RoboZonky/robozonky/wiki/2FA-a-RoboZonky#2-rychl%C3%A9-spu%C5%A1t%C4%9Bn%C3%AD-robota.
