### ISSUE TITLE
Vyjimka pri prodeji participaci

### ISSUE THREAD

**Issue by vvondra** [RoboZonky/robozonky#570]
Verze: 6.1.1
Runtime: Docker

```
22:16:21.619 WARN  Listener class com.github.robozonky.notifications.listeners.InvestmentSoldEventListener failed for LazyEventImpl{eventType=interface com.github.robozonky.api.notifications.InvestmentSoldEvent}.
java.lang.IllegalStateException: Event processing failed.
	at com.github.robozonky.notifications.listeners.AbstractListener.handle(AbstractListener.java:178) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.app.events.SessionEvents.fireAny(SessionEvents.java:123) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.app.events.SessionEvents$EventTriggerRunnable.run(SessionEvents.java:196) ~[robozonky-app-6.1.1-full.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1699) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.github.robozonky.internal.state.StateModifier.put(StateModifier.java:55) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.internal.state.StateModifier.put(StateModifier.java:42) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.notifications.Counter.lambda$store$2(Counter.java:78) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.internal.state.InstanceStateImpl.execute(InstanceStateImpl.java:44) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.internal.state.InstanceStateImpl.reset(InstanceStateImpl.java:55) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.notifications.Counter.store(Counter.java:78) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.notifications.Counter.increase(Counter.java:96) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.notifications.AbstractTargetHandler.offer(AbstractTargetHandler.java:144) ~[robozonky-app-6.1.1-full.jar:?]
	at com.github.robozonky.notifications.listeners.AbstractListener.handle(AbstractListener.java:175) ~[robozonky-app-6.1.1-full.jar:?]
	... 4 more
```

Strategie: https://robozonky.github.io/konfigurace-strategie/?fbclid=IwAR3QBeL8lSewipIIoYrxIffoPunMIFS6AfVQZ2ixvPltZowSbjQdfcaYnFY#Njt7ImgiOnsiYSI6MCwiYiI6WyIyIiwiMS40LjIwMjAiLCIzMC4zLjIwMjAiXSwiYyI6WzFdLCJkIjoyMDAsImQxIjoyMDAsImcxIjoxfSwiaiI6WzIwMCwyMDAsMjAwLDIwMCwyMDAsMjAwLDIwMCwyMDAsMjAwLDIwMCwyMDBdLCJqMSI6WzIwMCwyMDAsMjAwLDIwMCwyMDAsMjAwLDIwMCwyMDAsMjAwLDIwMCwyMDBdLCJrIjp7Im8iOjJ9LCJsIjp7Im0iOjEsIm4iOlt7InMiOjMsInQiOnsiVCI6WzVdLCJNIjpbMywxXSwiUCI6ZmFsc2V9LCJ1Ijp7fX1dfX0=

**Comment by triceo** [comment]
Díky, mrknu na to.

**Comment by triceo** [comment]
Oprava bude v 6.2.0 někdy během 14 dní.
Jen jedna poznámka k odkázané strategii - s problémem to nijak nesouvisí, ale ta podmínka pro Zonky exit daleko v minulosti je tam schválně? Zaujalo mě to.

**Comment by vvondra** [comment]
Zadny zamer, je to akorat vysledek pokusu nakonfigurovat strategii aby opustila Zonky ASAP (a rikal jsem si, ze konfigurace v minulosti to nasimuluje, jako kdyby nekdo uz mel robota ve stavu opousteni nejakou dobu).
