### ISSUE TITLE
Docs: Emailové notifikace

### ISSUE THREAD

**Issue by panther7** [RoboZonky/robozonky#580]
Ahoj, narazil jsem ve wiki na nesrovnalosti ohledně emailových notifikací.

https://github.com/RoboZonky/robozonky/wiki/E-mailov%C3%A9-notifikace

Konkrétně:
* Soubor se již jmenuje `robozonky-notifications.cfg` a obsahuje položky `email.*`
* Na některých místech je `maxHourlyEmails` a někde `hourlyMaxEmails`, prosím o sjednocení, co je správně. Týká se i odkazů na ukázky.
* A možná další věci, kterých jsem si nevšiml.

**Comment by panther7** [comment]
Proč to teď řeším, protože mi poslední dny robot posílá stovky mailů za hodinu, že došlo k chybě, ale nedaří se mi ho zkrotit...

Zkoušel jsem
```
email.roboZonkyDaemonResumed.maxHourlyEmails=2
email.roboZonkyDaemonSuspended.maxHourlyEmails=2
```
i s varaintou `hourlyMaxEmails` a pořád spamuje. Zkoušel jsem stable verzi 6.2.3 i 6.3.0.cr2

**Comment by triceo** [comment]
Na dokumentaci se podívám, ale víc mě zajímají ty stovky e-mailů.
Co je v nich?

**Comment by panther7** [comment]
@triceo 
Převážně, že se nedá stáhnout portfolio.

```
Uvnitř RoboZonky démona došlo k chybě, v jejmž důsledku byl robot pozastaven. Funkčnost robota bude obnovena hned, jak to bude možné. Následují detailní informace o chybě:

java.lang.IllegalStateException: Failed loading portfolio overview.
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.lambda$getOverview$11(RemotePortfolioImpl.java:126)
	at com.github.robozonky.internal.util.functional.Either.lambda$getOrElseThrow$0(Either.java:54)
	at java.base/…401)
	at com.github.robozonky.internal.util.functional.Either.getOrElseThrow(Either.java:54)
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.getOverview(RemotePortfolioImpl.java:126)
	at com.github.robozonky.app.daemon.InvestingSession.lambda$invest$3(InvestingSession.java:66)
	at com.github.robozonky.strategy.natural.NaturalLanguageInvestmentStrategy.recommend(NaturalLanguageInvestmentStrategy.java:43)
	at com.github.robozonky.app.daemon.InvestingSession.lambda$invest$5(InvestingSession.java:65)
	at java.base/…271)
	at java.base/…177)
	at java.base/…195)
	at java.base/…177)
	at java.base/…195)
	at java.base/…602)
	at com.github.robozonky.internal.util.stream.PagingSpliterator.tryAdvance(PagingSpliterator.java:76)
	at java.base/…127)
	at java.base/…502)
	at java.base/…488)
	at java.base/…474)
	at java.base/…150)
	at java.base/…173)
	at java.base/…234)
	at java.base/…497)
	at com.github.robozonky.app.daemon.InvestingSession.invest(InvestingSession.java:70)
	at com.github.robozonky.app.daemon.InvestingSession.invest(InvestingSession.java:54)
	at com.github.robozonky.app.daemon.StrategyExecutor.invest(StrategyExecutor.java:102)
	at java.base/…258)
	at com.github.robozonky.app.daemon.StrategyExecutor.get(StrategyExecutor.java:121)
	at com.github.robozonky.app.daemon.Skippable.run(Skippable.java:69)
	at com.github.robozonky.internal.async.TaskDescriptor.lambda$new$0(TaskDescriptor.java:48)
	at java.base/…800)
	at java.base/…130)
	at java.base/…630)
	at java.base/…832)
Caused by: java.lang.IllegalStateException: Failed fetching remote portfolio.
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.lambda$getRemoteData$6(RemotePortfolioImpl.java:98)
	at com.github.robozonky.internal.util.functional.Either.lambda$getOrElseThrow$0(Either.java:54)
	at java.base/…401)
	at com.github.robozonky.internal.util.functional.Either.getOrElseThrow(Either.java:54)
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.getRemoteData(RemotePortfolioImpl.java:98)
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.getTotal(RemotePortfolioImpl.java:103)
	at com.github.robozonky.app.tenant.PortfolioOverviewImpl.(PortfolioOverviewImpl.java:37)
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.lambda$new$1(RemotePortfolioImpl.java:56)
	at com.github.robozonky.internal.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:57)
	at com.github.robozonky.internal.async.ReloadableImpl.get(ReloadableImpl.java:51)
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.getOverview(RemotePortfolioImpl.java:125)
	... 29 more
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:258)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:234)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:62)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:151)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy49.items(Unknown Source)
	at com.github.robozonky.internal.remote.Api.call(Api.java:61)
	at com.github.robozonky.internal.remote.Api.call(Api.java:82)
	at com.github.robozonky.internal.remote.PaginatedApi.execute(PaginatedApi.java:89)
	at com.github.robozonky.internal.remote.PaginatedApi.execute(PaginatedApi.java:84)
	at com.github.robozonky.internal.remote.PaginatedApi.execute(PaginatedApi.java:78)
	at com.github.robozonky.internal.remote.PaginatedApi.execute(PaginatedApi.java:105)
	at com.github.robozonky.internal.remote.PaginatedApi.execute(PaginatedApi.java:94)
	at com.github.robozonky.internal.remote.EntityCollectionPageSource.fetch(EntityCollectionPageSource.java:50)
	at com.github.robozonky.internal.util.stream.PagingSpliterator.build(PagingSpliterator.java:69)
	at com.github.robozonky.internal.util.stream.PagingStreams.lambda$build$0(PagingStreams.java:41)
	at java.base/…405)
	at java.base/…234)
	at java.base/…578)
	at com.github.robozonky.app.tenant.RemoteData.getAmountsBlocked(RemoteData.java:60)
	at com.github.robozonky.app.tenant.RemoteData.load(RemoteData.java:52)
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.lambda$new$0(RemotePortfolioImpl.java:50)
	at com.github.robozonky.internal.async.AbstractReloadableImpl.lambda$getOperation$0(AbstractReloadableImpl.java:57)
	at com.github.robozonky.internal.async.ReloadableImpl.get(ReloadableImpl.java:51)
	at com.github.robozonky.app.tenant.RemotePortfolioImpl.getRemoteData(RemotePortfolioImpl.java:97)
	... 35 more

```

**Comment by triceo** [comment]
Zítra to nahlásím na Zonky. Tohle nebude chyba v robotu, rozbili něco na serveru.

**Comment by panther7** [comment]
A logy taky rostou mega rychle, za necelou hodinu přes 4MB.

[robozonky.log](https://github.com/RoboZonky/robozonky/files/5838890/robozonky.log)

**Comment by triceo** [comment]
Dostal jsem echo ze Zonky, že by problém měl být vyřešený. Nicméně na dokumentaci se i tak podívám.

**Comment by panther7** [comment]
Díky, ýž mu nechodí emaily, mimochodem, to extrémní logování je v pořádku? Denní log přes 130MB.

**Comment by triceo** [comment]
Dokumentaci jsem právě aktualizoval.

Denní log 130 MB není v pořádku, ale ve chvíli, kdy Zonky na každý dotaz vyhodí výjimku, se to bohužel bude stávat. Robot je nastavený tak, aby výjimky zaznamenával - od toho koneckonců log je.
